# Generated by Django 5.2.7 on 2025-11-24 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_create_connector_user'),
        ('organizations', '0003_organization_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ANALYST', 'Analyst'), ('VIEWER', 'Viewer')], default='ANALYST', help_text="The user's role, which determines their permissions.", max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
