# Generated by Django 5.2.7 on 2025-11-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_customuser_role_alter_customuser_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ANALYST', 'Analyst'), ('REVIEWER', 'Reviewer'), ('VIEWER', 'Viewer')], default='ANALYST', help_text="The user's role, which determines their permissions.", max_length=10),
        ),
    ]
