# Generated by Django 5.2.7 on 2025-11-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Optional profile avatar image (requires Pillow).', null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text="Short 'About Me' summary.", max_length=500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(blank=True, help_text='e.g. Senior Threat Hunter', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='slack_handle',
            field=models.CharField(blank=True, help_text='Slack username or handle (e.g. @hunter01)', max_length=50),
        ),
    ]
