# Generated by Django 5.2.7 on 2025-12-09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_customuser_avatar_customuser_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAiCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI GPT'), ('anthropic', 'Anthropic Claude')], max_length=32)),
                ('encrypted_key', models.TextField()),
                ('key_fingerprint', models.CharField(blank=True, help_text='SHA-256 hex of the raw key for auditing', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_credentials', to='identity.customuser')),
            ],
            options={
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
