# Generated by Django 5.2.7 on 2025-12-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_useraicredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_notify_chat_message',
            field=models.BooleanField(default=False, help_text='Email me when I have a new chat message'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_notify_review_approved',
            field=models.BooleanField(default=True, help_text='Email me when my review is approved'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_notify_system_message',
            field=models.BooleanField(default=False, help_text='Email me when there is a new system message'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_notify_workbench_edited',
            field=models.BooleanField(default=True, help_text='Email me when someone edits my workbench'),
        ),
    ]
