# Generated by Django 5.2.7 on 2026-05-10 07:30

import django.db.models.deletion
import identity.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0008_password_reset_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='MfaAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('TOTP_ENROLL_STARTED', 'TOTP enroll started'), ('TOTP_ENROLL_CONFIRMED', 'TOTP enroll confirmed'), ('TOTP_DISABLED', 'TOTP disabled'), ('BACKUP_CODES_REGENERATED', 'Backup codes regenerated'), ('LOGIN_CHALLENGE_CREATED', 'MFA login challenge created'), ('LOGIN_SUCCESS', 'MFA login success'), ('LOGIN_FAILED', 'MFA login failed'), ('LOGIN_LOCKED', 'MFA locked'), ('ADMIN_RESET', 'Admin reset MFA')], max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MfaLoginChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.CharField(default=identity.models._default_mfa_challenge_id, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_login_challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMfaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totp_enabled', models.BooleanField(default=False)),
                ('totp_secret_encrypted', models.TextField(blank=True, default='')),
                ('pending_totp_secret_encrypted', models.TextField(blank=True, default='')),
                ('backup_codes_hashes', models.JSONField(blank=True, default=list)),
                ('backup_codes_generated_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebAuthnChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.CharField(default=identity.models._default_mfa_challenge_id, max_length=64, unique=True)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('challenge_type', models.CharField(choices=[('REGISTRATION', 'Registration'), ('AUTHENTICATION', 'Authentication'), ('PASSWORDLESS', 'Passwordless')], max_length=16)),
                ('challenge', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('credential_id', models.TextField(unique=True)),
                ('public_key', models.TextField()),
                ('sign_count', models.PositiveIntegerField(default=0)),
                ('transports', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
