"""
(c) 2026 M3C4N1SM0 & All kinds of AI Bots

Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from corsheaders.defaults import default_headers

# --- ADD THIS HELPER ---
def get_secret(secret_name, default_env_var=None):
    secret_path = f"/run/secrets/{secret_name}"
    try:
        with open(secret_path, 'r') as f:
            return f.read().strip()
    except FileNotFoundError:
        pass

    if default_env_var:
        # Support standard Docker-style *_FILE env variables even when
        # running without the entrypoint helper (e.g., direct manage.py).
        file_env_var = f"{default_env_var}_FILE"
        file_path = os.environ.get(file_env_var)
        if file_path:
            try:
                with open(file_path, 'r') as f:
                    return f.read().strip()
            except FileNotFoundError:
                pass

        return os.environ.get(default_env_var)

    return None
# --- END HELPER ---

# Import user-configurable deployment settings from backend/hefaistos/settings.py.
# Users should edit that file instead of this one.
try:
    from hefaistos.settings import EMAIL_CONFIGURATION, MAILGUN_CONFIGURATION
except ImportError:
    EMAIL_CONFIGURATION = {}
    MAILGUN_CONFIGURATION = {}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1(0%e4$5@d+zdt(b0mwpqg=$479a=7lq-m6hqi-h0p-3*2hns)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'channels',
    'django_elasticsearch_dsl',
    'organizations',
    'identity',
    'rest_framework',
    'graphene_django',
    'graphql_jwt',
    'rules',
    'playbooks',
    'advops',
    'taggit',
    'tags',
    'data_catalog',
    'platform_data',
    'import_export',
    'review',
    'notifications',
    'knowledge',
    'services',
    'log_catalog',
    'ai_assistant',
    'news',  # News and announcements feature
    'ach',
    'pain_points',  # Pain Points feedback board
    'mgmt_reports',  # Management reports and AI assistant
    'lsp_server.apps.LspServerConfig',  # SyntaxTide LSP server management
    'webhooks',     # CoreTide webhook handlers
]

MIDDLEWARE = [
    # CSD security middleware - DISABLED temporarily to restore access
    # These validations should be handled by nginx, not Django
    # 'core.middleware.ContentLengthValidationMiddleware',
    # 'core.middleware.RequestBodyConsumptionMiddleware',
    'core.middleware.CSDSecurityHeadersMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'core.middleware.CORSPrivateNetworkMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --- Admin IP Restriction ---
# Only these IP ranges can access /admin/
# Configure via ADMIN_ALLOWED_IP_RANGES env var (comma-separated CIDR ranges).
# Default includes localhost and Docker internal networks only.
_admin_ip_env = os.environ.get('ADMIN_ALLOWED_IP_RANGES', '127.0.0.1/32,::1/128,10.0.0.0/8,172.16.0.0/12')
ADMIN_ALLOWED_IP_RANGES = [ip.strip() for ip in _admin_ip_env.split(',') if ip.strip()]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'

# Django Channels layer (in-memory for single-server deployments;
# replace with Redis layer for multi-process production setups)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': get_secret('db_password', 'DB_PASSWORD'), # Reads from /run/secrets/db_password
        'HOST': os.environ.get('DB_HOST'),
        'PORT': '5432',
    }
}

# --- Local development fallback: use SQLite if no DB env vars are set ---
if not os.environ.get('DB_NAME'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user uploads / generated snapshots)
# MEDIA_URL is set dynamically below, after CSRF_TRUSTED_ORIGINS is defined,
# to ensure generated URLs stay correct behind reverse proxies.
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'identity.CustomUser'

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

# Graphene-Django Configuration
GRAPHENE = {
    'SCHEMA': 'core.schema.schema',
    'MIDDLEWARE': [
        'graphql_jwt.middleware.JSONWebTokenMiddleware',
        'core.graphql_logging.GraphQLLogMiddleware',
    ],
}

# Authentication
AUTHENTICATION_BACKENDS = [
    'graphql_jwt.backends.JSONWebTokenBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Configure the JWT header
GRAPHQL_JWT = {
    "JWT_AUTH_HEADER_PREFIX": "Bearer",
    # Extend token expiration for service accounts (connector)
    # Default is 5 minutes which is too short for long-running connectors
    "JWT_EXPIRATION_DELTA": timedelta(days=7),
    "JWT_REFRESH_EXPIRATION_DELTA": timedelta(days=30),
    "JWT_VERIFY_EXPIRATION": True,
}

# Elasticsearch Configuration
ELASTICSEARCH_DSL = {
    'default': {
        'hosts': 'http://elasticsearch:9200'
    },
}

# CORS Configuration
# mitre-attack.github.io is always allowed so the ATT&CK Navigator can fetch
# coverage layer JSON from /api/coverage/ regardless of deployment domain.
# Add deployment-specific origins via the CORS_ALLOWED_ORIGINS env var
# (comma-separated list, e.g. "https://app.example.com,http://app.example.com").
_cors_env = os.environ.get('CORS_ALLOWED_ORIGINS', '')
CORS_ALLOWED_ORIGINS = ["https://mitre-attack.github.io"] + [
    o.strip() for o in _cors_env.split(',') if o.strip()
]

# Allow CORS for all API paths (including /api/coverage/ so the ATT&CK Navigator
# and the frontend validation fetch can read the coverage layer JSON cross-origin)
CORS_URLS_REGEX = r'^/(graphql|api/.*)$'
# Allow sending cookies/authorization headers cross-origin (JWT via Authorization header)
CORS_ALLOW_CREDENTIALS = True
# Ensure authorization & custom headers are accepted in preflight
CORS_ALLOW_HEADERS = list(default_headers) + [
    'authorization',
    'content-type',
]

# Expose headers so frontend can read them cross-origin
CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']

# --- CSRF / Proxy settings for HTTPS behind Nginx ---
# Trust origins specified via the CSRF_TRUSTED_ORIGINS env var (comma-separated).
# Default covers localhost only; set this to your server's public URL in production.
_csrf_env = os.environ.get('CSRF_TRUSTED_ORIGINS', 'https://localhost,http://localhost')
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_env.split(',') if o.strip()]

# Media files are served by Nginx from the /media/ path on whatever host/port the
# user is accessing.  Using a relative URL means avatar and snapshot URLs are always
# correct regardless of the deployment domain – no hardcoded host required.
MEDIA_URL = '/media/'

# Ensure Django is aware it's behind a HTTPS proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Use secure cookies when served over HTTPS
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Set SameSite to Lax for admin forms over proxy
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Respect X-Forwarded-Host from proxy
USE_X_FORWARDED_HOST = True

# Logging configuration for GraphQL tracing
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s',
        },
        'mcs_json': {
            '()': 'core.mcs_logging.MCSJsonFormatter',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
        'security_console': {
            'class': 'logging.StreamHandler',
            'formatter': 'mcs_json',
        },
        'security_elasticsearch': {
            '()': 'core.mcs_logging.ElasticsearchMCSHandler',
        },
    },
    'loggers': {
        'security.mcs': {
            'handlers': ['security_console', 'security_elasticsearch'],
            'level': os.environ.get('HEFAISTOS_SECURITY_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'graphql': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'rules.deployers': {
            'handlers': ['console'],
            'level': os.environ.get('HEFAISTOS_DEPLOYER_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}

# --- RABBITMQ CONFIGURATION ---
RABBITMQ_HOST = os.environ.get('RABBITMQ_HOST', 'rabbitmq')
RABBITMQ_PORT = os.environ.get('RABBITMQ_PORT', 5672)
RABBITMQ_USER = os.environ.get('RABBITMQ_USER', 'guest')
RABBITMQ_PASS = get_secret('rabbitmq_pass', 'RABBITMQ_PASS')

# --- FIELD ENCRYPTION KEY ---
# This key is used for encrypting credentials (e.g., Git tokens) in the database.
# WARNING: If you lose this key, all encrypted data will be lost.
# Configure via env var `FIELD_ENCRYPTION_KEY` (base64 urlsafe),
# `FIELD_ENCRYPTION_KEY_FILE` pointing to a file, or
# legacy `FIELD_ENCRYPTION_KEY_PATH` (kept for backward compatibility).

FIELD_ENCRYPTION_KEY = get_secret('field_key', 'FIELD_ENCRYPTION_KEY')
if not FIELD_ENCRYPTION_KEY:
    field_key_path = os.environ.get('FIELD_ENCRYPTION_KEY_PATH')
    if field_key_path:
        try:
            with open(field_key_path, 'r') as f:
                FIELD_ENCRYPTION_KEY = f.read().strip()
        except FileNotFoundError:
            pass

if FIELD_ENCRYPTION_KEY:
    FIELD_ENCRYPTION_KEY = FIELD_ENCRYPTION_KEY.encode()

if not FIELD_ENCRYPTION_KEY:
    # In production, require explicit configuration
    if not DEBUG:
        raise RuntimeError(
            "FIELD_ENCRYPTION_KEY not configured. Set FIELD_ENCRYPTION_KEY, "
            "FIELD_ENCRYPTION_KEY_FILE, or FIELD_ENCRYPTION_KEY_PATH."
        )
    # In development, warn and leave it unset (encryption helpers will no-op)
    # To enable encryption locally, set FIELD_ENCRYPTION_KEY or FIELD_ENCRYPTION_KEY_FILE.

# Increase max request payload memory to 20MB to support base64-encoded 10MB document uploads
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 20 MB

# --- EMAIL / SMTP CONFIGURATION ---
# Configure SMTP via (in priority order):
#   1. Docker secrets under /run/secrets/email_password
#   2. Environment variables (set in docker-compose.yml)
#   3. backend/hefaistos/settings.py  ← recommended place for users to set defaults
# Supported vars: EMAIL_HOST, EMAIL_PORT, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD, EMAIL_USE_TLS, EMAIL_USE_SSL, DEFAULT_FROM_EMAIL

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST') or EMAIL_CONFIGURATION.get('EMAIL_HOST', 'smtp.mailgun.org')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT') or EMAIL_CONFIGURATION.get('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = get_secret('email_password', 'EMAIL_HOST_PASSWORD') or ''
_email_use_tls_env = os.environ.get('EMAIL_USE_TLS')
EMAIL_USE_TLS = _email_use_tls_env.lower() == 'true' if _email_use_tls_env is not None else EMAIL_CONFIGURATION.get('EMAIL_USE_TLS', True)
_email_use_ssl_env = os.environ.get('EMAIL_USE_SSL')
EMAIL_USE_SSL = _email_use_ssl_env.lower() == 'true' if _email_use_ssl_env is not None else EMAIL_CONFIGURATION.get('EMAIL_USE_SSL', False)
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL') or os.environ.get('EMAIL_HOST_USER') or EMAIL_CONFIGURATION.get('DEFAULT_FROM_EMAIL', 'noreply@localhost')

# Optional: fail silently in development if SMTP not configured
if DEBUG and (not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD):
    # Use console backend in dev to avoid SMTP errors
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# --- MISP CONFIGURATION (global / legacy fallback) ---
# Per-organization MISP instances are now managed via the web UI (Settings → Repositories → MISP Instances)
# and stored in the database.  These global env vars are kept for backward compatibility and for the
# threat_intel_connector service which still pulls from a single global MISP instance.
# New deployments should leave these unset and configure MISP per-organization via the UI instead.
MISP_URL = os.environ.get('MISP_URL', '').rstrip('/')
MISP_API_KEY = get_secret('misp_key', 'MISP_API_KEY')
MISP_VERIFY_SSL = os.environ.get('MISP_VERIFY_SSL', 'true').lower() == 'true'
MISP_ENABLED = bool(MISP_URL and MISP_API_KEY)

# Frontend URL used in emails (login links etc.)
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'https://localhost')

# Public canonical base URL used for externally shareable links when running
# behind one or more reverse proxies/load balancers.
PUBLIC_BASE_URL = os.environ.get('PUBLIC_BASE_URL', '').rstrip('/')

# WebAuthn / FIDO2 settings (required for security-key MFA/passwordless)
WEBAUTHN_RP_ID = os.environ.get('WEBAUTHN_RP_ID', 'localhost')
WEBAUTHN_ORIGIN = os.environ.get('WEBAUTHN_ORIGIN', FRONTEND_URL.rstrip('/'))

# --- CORETIDE WEBHOOK ---
# HMAC-SHA256 secret used to verify incoming deployment status webhooks from CoreTide.
# Set via the CORETIDE_WEBHOOK_SECRET environment variable or the Docker secret
# 'coretide_webhook_secret'.  When unset, signature verification is skipped (dev only).
CORETIDE_WEBHOOK_SECRET = get_secret('coretide_webhook_secret', 'CORETIDE_WEBHOOK_SECRET')

# Application metadata
HEFAISTOS_VERSION = "1.0"
HEFAISTOS_COPYRIGHT = "(c) 2026 Jan Pohl - m3c4n1sm0 and multiple AI bots"
HEFAISTOS_DESCRIPTION = "Detection Engineering Platform"
