# Generated by Django 5.2.7 on 2025-11-28 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('gemini_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('claude_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_model', models.CharField(choices=[
                    ('GPT-5.2', 'GPT-5.2'),
                    ('GPT-5.1', 'GPT-5.1'),
                    ('GPT-5', 'GPT-5'),
                    ('GPT-4', 'GPT-4'),
                    ('GPT-3.5', 'GPT-3.5'),
                    ('GEMINI-3-PRO-PREVIEW', 'Gemini 3 Pro Preview'),
                    ('GEMINI-3-FLASH-PREVIEW', 'Gemini 3 Flash Preview'),
                    ('GEMINI-3.0-PRO', 'Gemini 3.0 Pro'),
                    ('GEMINI-2.5-FLASH', 'Gemini 2.5 Flash'),
                    ('GEMINI-PRO', 'Gemini (Legacy)'),
                    ('GEMINI-2.5-FLASH-LITE', 'Gemini 2.5 Flash Lite'),
                    ('CLAUDE-OPUS-4.5', 'Claude Opus 4.5'),
                    ('CLAUDE-SONNET-4.5', 'Claude Sonnet 4.5'),
                    ('CLAUDE-HAIKU-4.5', 'Claude Haiku 4.5'),
                    ('CLAUDE-3', 'Claude 3')
                ], default='GEMINI-3-FLASH-PREVIEW', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
