# Generated by Django 5.2.7 on 2025-12-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraisettings',
            name='preferred_model',
            field=models.CharField(choices=[('GPT-4', 'GPT-4'), ('GPT-3.5', 'GPT-3.5'), ('GEMINI-PRO', 'Gemini (Legacy)'), ('GEMINI-2.5-FLASH', 'Gemini 2.5 Flash'), ('GEMINI-3.0-PRO', 'Gemini 3.0 Pro'), ('GEMINI-2.5-FLASH-LITE', 'Gemini 2.5 Flash Lite'), ('CLAUDE-3', 'Claude 3')], default='GPT-4', max_length=50),
        ),
    ]
