# Generated by Django 5.2.7 on 2025-12-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_alter_useraisettings_preferred_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraisettings',
            name='claude_api_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraisettings',
            name='gemini_api_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraisettings',
            name='openai_api_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
