# Generated by Django 5.2.7 on 2026-05-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0013_merge_20260529_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aigenerationtask',
            name='task_type',
            field=models.CharField(choices=[('GENERATE_RULE', 'Generate Rule'), ('SUGGEST_IMPROVEMENTS', 'Suggest Improvements'), ('GENERATE_SIMILAR', 'Generate Similar Rules')], max_length=30),
        ),
        migrations.AlterField(
            model_name='orgaisettings',
            name='org_preferred_model',
            field=models.CharField(blank=True, default='', help_text='Default model for org-wide AI usage, e.g. GPT-5.5, GEMINI-3.5-FLASH, CLAUDE-SONNET-4.6, OLLAMA', max_length=50),
        ),
    ]
