# Generated by Django 5.2.7 on 2026-06-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0014_alter_aigenerationtask_task_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aigenerationtask',
            name='task_type',
            field=models.CharField(
                choices=[
                    ('GENERATE_RULE', 'Generate Rule'),
                    ('SUGGEST_IMPROVEMENTS', 'Suggest Improvements'),
                    ('GENERATE_SIMILAR', 'Generate Similar Rules'),
                    ('POPULATE_THREAT_REPORT', 'Populate Workbench from Threat Report'),
                ],
                max_length=30,
            ),
        ),
    ]
