# Generated by Django 5.2.7 on 2025-11-21 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='organizations.entity'),
        ),
    ]
