# Generated by Django 5.2.7 on 2026-03-23 11:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_mispinstance'),
        ('playbooks', '0032_playbookgraph_opentide'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InitTideConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repository_url', models.CharField(help_text='Git repository URL (SSH or HTTPS)', max_length=512)),
                ('branch', models.CharField(default='main', max_length=255)),
                ('_ssh_private_key', models.TextField(blank=True, db_column='ssh_private_key', help_text='Encrypted SSH private key (do not access directly)', null=True)),
                ('ssh_public_key', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(default=False)),
                ('auto_commit', models.BooleanField(default=False)),
                ('require_peer_review', models.BooleanField(default=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inittide_configuration', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'InitTide Configuration',
            },
        ),
        migrations.CreateModel(
            name='PlaybookCommitHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commit_sha', models.CharField(max_length=40)),
                ('commit_message', models.TextField()),
                ('file_path', models.CharField(help_text='Relative path within the InitTide repository', max_length=512)),
                ('branch', models.CharField(max_length=255)),
                ('committed_at', models.DateTimeField(auto_now_add=True)),
                ('deployment_status', models.CharField(choices=[('PENDING', 'Pending'), ('DEPLOYED', 'Deployed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playbook_commits', to=settings.AUTH_USER_MODEL)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit_history', to='playbooks.playbookgraph')),
            ],
            options={
                'verbose_name': 'Playbook Commit History',
                'verbose_name_plural': 'Playbook Commit Histories',
                'ordering': ['-committed_at'],
            },
        ),
    ]
