# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_inittide_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookcommithistory',
            name='deployed_to_siems',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of SIEM platform names successfully deployed to',
            ),
        ),
    ]
