# Generated by Django 5.2.7 on 2026-05-29 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pain_points', '0004_delete_legacy'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='painpoint',
            new_name='pain_points_organiz_715dd4_idx',
            old_name='pain_points_organiza_idx',
        ),
        migrations.RenameIndex(
            model_name='painpoint',
            new_name='pain_points_priorit_13c52d_idx',
            old_name='pain_points_priorit_idx',
        ),
        migrations.RenameIndex(
            model_name='painpoint',
            new_name='pain_points_author__c3137b_idx',
            old_name='pain_points_author_idx',
        ),
        migrations.RenameIndex(
            model_name='painpointcomment',
            new_name='pain_points_pain_po_78e5c9_idx',
            old_name='pain_points_pain_po_idx',
        ),
        migrations.RenameIndex(
            model_name='painpointcomment',
            new_name='pain_points_author__87d400_idx',
            old_name='pain_points_author_7f90c0_idx',
        ),
        migrations.RenameIndex(
            model_name='painpointcomment',
            new_name='pain_points_parent__35e295_idx',
            old_name='pain_points_parent_c_idx',
        ),
        migrations.RenameIndex(
            model_name='painpointcomment',
            new_name='pain_points_pain_po_c13cd5_idx',
            old_name='pain_points_pp_pc_idx',
        ),
    ]
