# Generated by Django 5.2.7 on 2025-11-12

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_taggedk-article'),
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='tags',
            field=models.ManyToManyField(blank=True, through='tags.TaggedKBArticle', to='tags.tenanttag'),
        ),
    ]
