# Generated by Django 5.2.7 on 2025-11-12 15:49

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_article_tags'),
        ('tags', '0003_merge_20251112_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebasearticle',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='tags.TaggedKBArticle', to='tags.TenantTag', verbose_name='Tags'),
        ),
    ]
