# Generated by Django 5.2.7 on 2026-05-29 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advops', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='advopsreport',
            new_name='advops_advo_status_42fdb1_idx',
            old_name='advops_advo_status_priority_idx',
        ),
    ]
