"""
AI-Powered OpenTIDE Schema Enrichment Engine

Provides intelligent conversion of user-friendly workbench inputs into
OpenTIDE-compliant structured metadata following the ShareTide schema
specifications (BDR v2.0, MDR v2.1, DOM v1.0).

IMPORTANT: AI enrichment covers ONLY metadata fields such as BDR schema,
MDR response procedures, platform/target mapping, and DOM descriptive
signals. Detection rules (KQL, SPL, Sigma, WAZUH queries) are ALWAYS
provided exclusively by the user and are never generated by AI.
"""

import json
import logging
import re
import uuid
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Vocabulary constants (aligned with ShareTide schema v2.0 / v2.1)
# ---------------------------------------------------------------------------
# Fallback values used when the ShareTideIndexEntry database table is
# unavailable or empty.  The helper _get_vocab() always prefers database
# values so that administrators can update them without code changes.

BDR_CRITICALITY_VALUES = [
    'Emergency', 'Severe', 'High', 'Medium', 'Low',
    'Baseline - Negligible', 'Baseline - Minor',
]

BDR_DOMAINS = [
    'Enterprise', 'Public Cloud', 'Private Cloud', 'Mobile',
    'SaaS', 'Networking', 'OSINT', 'Embedded', 'IoT', 'Industrial',
]

BDR_TARGETS = [
    'Critical Documents', 'Personal Information', 'Identity Services',
    'Workstations', 'Servers', 'Network Infrastructure', 'Cloud Resources',
    'Email', 'Applications', 'Databases', 'Directory', 'Credentials',
    'Mobile Devices', 'IoT Devices', 'Industrial Systems',
]

BDR_PLATFORMS = [
    'Windows', 'Linux', 'macOS', 'AWS', 'Azure', 'GCP',
    'Active Directory', 'Azure AD', 'Office 365', 'Google Workspace',
    'Kubernetes', 'Docker', 'VMware', 'Network Devices', 'Mobile',
]

MDR_ALERT_SEVERITIES = ['Critical', 'High', 'Medium', 'Low', 'Informational']

MDR_RESPONDERS = ['CSIRC', 'CATCH', 'MARTI', 'S1-SA']

DOM_PRIORITIES = ['Critical', 'High', 'Medium', 'Low']

# ---------------------------------------------------------------------------
# Vocabulary accessor – prefers ShareTide DB index, falls back to constants
# ---------------------------------------------------------------------------

_VOCAB_FALLBACKS = {
    'bdr_criticality': BDR_CRITICALITY_VALUES,
    'bdr_domains': BDR_DOMAINS,
    'bdr_targets': BDR_TARGETS,
    'bdr_platforms': BDR_PLATFORMS,
    'mdr_alert_severities': MDR_ALERT_SEVERITIES,
    'mdr_responders': MDR_RESPONDERS,
    'dom_priorities': DOM_PRIORITIES,
}


def _get_vocab(category: str) -> list:
    """Return vocabulary list for *category* from DB, falling back to constants."""
    try:
        from platform_data.models import ShareTideIndexEntry
        values = list(
            ShareTideIndexEntry.objects
            .filter(category=category)
            .order_by('sort_order', 'value')
            .values_list('value', flat=True)
        )
        if values:
            return values
    except Exception:
        pass
    return _VOCAB_FALLBACKS.get(category, [])


# ---------------------------------------------------------------------------
# Helper: unified AI provider call
# ---------------------------------------------------------------------------

def call_ai_provider(
    prompt: str,
    user_settings,
    response_format: str = "json",
    *,
    system_prompt: str | None = None,
    user_prompt: str | None = None,
    temperature: float = 0.1,
    max_tokens: int = 4000,
) -> str:
    """
    Unified AI provider call with error handling.

    Reuses the provider resolution logic from ai_assistant/engine.py and
    supports OpenAI, Gemini, Claude and Ollama providers.

    Args:
        prompt: Backward-compatible fallback prompt when user_prompt is omitted.
        user_settings: UserAISettings (or effective OrgAISettings) instance.
        response_format: "json" or "text".
        system_prompt: Optional system-role instruction text.
        user_prompt: Optional user-role task text.
        temperature: Model temperature.
        max_tokens: Max output token budget where supported.

    Returns:
        Raw AI response text, or empty string on failure.
    """
    try:
        import openai as _openai  # type: ignore
    except ImportError:
        _openai = None
    try:
        import google.generativeai as _genai  # type: ignore
    except ImportError:
        _genai = None
    try:
        import anthropic as _anthropic  # type: ignore
    except ImportError:
        _anthropic = None

    from ai_assistant.engine import (
        _call_ollama,
        _map_claude,
        _map_gemini,
        _map_gpt,
        _openai_chat_create_with_token_fallback,
        _resolve_provider,
        build_available,
    )

    available = build_available(user_settings)
    if not available:
        return ''

    provider = _resolve_provider(user_settings, available)
    system_text = (system_prompt or "You are a strict cybersecurity data extraction assistant.").strip()
    user_text = (user_prompt if user_prompt is not None else prompt or "").strip()
    if not user_text:
        return ''

    try:
        if 'GPT' in provider:
            if not user_settings.get_openai_key() or _openai is None:
                return ''

            client = _openai.OpenAI(api_key=user_settings.get_openai_key())
            messages = [
                {"role": "system", "content": system_text},
                {"role": "user", "content": user_text},
            ]
            kwargs = {
                "temperature": temperature,
            }
            if response_format == "json":
                kwargs["response_format"] = {"type": "json_object"}
            response = _openai_chat_create_with_token_fallback(
                client,
                _map_gpt(provider),
                messages,
                max_tokens=max_tokens,
                **kwargs,
            )
            return response.choices[0].message.content or ''

        elif 'GEMINI' in provider:
            if not user_settings.get_gemini_key() or _genai is None:
                return ''

            _genai.configure(api_key=user_settings.get_gemini_key())
            model = _genai.GenerativeModel(_map_gemini(provider), system_instruction=system_text)
            generation_config = {
                "temperature": temperature,
                "max_output_tokens": max_tokens,
            }
            if response_format == "json":
                generation_config["response_mime_type"] = "application/json"
            response = model.generate_content(
                user_text,
                generation_config=generation_config,
            )
            return response.text or ''

        elif 'CLAUDE' in provider:
            if not user_settings.get_claude_key() or _anthropic is None:
                return ''

            client = _anthropic.Anthropic(api_key=user_settings.get_claude_key())
            message = client.messages.create(
                model=_map_claude(provider),
                max_tokens=max_tokens,
                system=system_text,
                messages=[{"role": "user", "content": user_text}],
            )
            return message.content[0].text or ''

        elif provider == 'OLLAMA':
            return _call_ollama(
                user_settings.get_ollama_url(),
                user_settings.get_ollama_model(),
                [
                    {"role": "system", "content": system_text},
                    {"role": "user", "content": user_text},
                ],
            )

        elif provider == 'AZURE-OPENAI':
            if _openai is None:
                return ''
            endpoint = getattr(user_settings, 'get_azure_openai_endpoint', lambda: '')()
            api_key = getattr(user_settings, 'get_azure_openai_key', lambda: '')()
            deployment = getattr(user_settings, 'get_azure_openai_deployment', lambda: '')()
            if not (endpoint and api_key and deployment):
                return ''
            client = _openai.AzureOpenAI(
                azure_endpoint=endpoint,
                api_key=api_key,
                api_version="2024-02-01",
            )
            messages = [
                {"role": "system", "content": system_text},
                {"role": "user", "content": user_text},
            ]
            kwargs = {
                "temperature": temperature,
            }
            if response_format == "json":
                kwargs["response_format"] = {"type": "json_object"}
            response = _openai_chat_create_with_token_fallback(
                client,
                deployment,
                messages,
                max_tokens=max_tokens,
                **kwargs,
            )
            return response.choices[0].message.content or ''

    except Exception as exc:
        logger.warning("AI provider call failed (%s): %s", provider, exc)

    return ''


def _parse_json_response(raw: str, fallback: Any) -> Any:
    """Strip optional markdown fences and parse JSON; return fallback on error."""
    if not raw:
        return fallback
    cleaned = raw.strip()
    if cleaned.startswith('```'):
        cleaned = re.sub(r'^```[a-zA-Z]*\n?', '', cleaned)
        cleaned = re.sub(r'\n?```$', '', cleaned.strip())
    try:
        return json.loads(cleaned)
    except Exception:
        return fallback


# ---------------------------------------------------------------------------
# 1. Detection type classification
# ---------------------------------------------------------------------------

def ai_classify_detection_type(playbook_data: Dict, user_settings) -> str:
    """
    Classify a detection use-case as THREAT or BUSINESS driven.

    Analyses the title, goal, technical context and any compliance keyword
    signals in the playbook fields.

    Args:
        playbook_data: Dict with keys: title, goal, technical_context, and
            optionally compliance (str).
        user_settings: UserAISettings (or effective settings) instance.

    Returns:
        "THREAT" or "BUSINESS"
    """
    system_prompt = (
        "You are a senior detection engineering architect. "
        "Classify detection use-cases and return only strict JSON."
    )
    user_prompt = (
        "Classify the following detection use-case as either THREAT-driven or BUSINESS-driven.\n\n"
        "THREAT-driven: focuses on adversary techniques, MITRE ATT&CK tactics, malware, threat actors.\n"
        "BUSINESS-driven: focuses on compliance requirements, policy violations, insider risk, "
        "data governance, regulatory obligations (GDPR, PCI-DSS, HIPAA, etc.).\n\n"
        'Output ONLY a JSON object with two keys: "classification" ("THREAT" or "BUSINESS") '
        'and "confidence" (0.0 to 1.0). No other text.\n\n'
        f"TITLE: {playbook_data.get('title', '')}\n"
        f"GOAL: {playbook_data.get('goal', '')}\n"
        f"TECHNICAL CONTEXT: {playbook_data.get('technical_context', '')}\n"
        f"COMPLIANCE: {playbook_data.get('compliance', '')}\n\n"
        "Return the JSON object only."
    )

    raw = call_ai_provider(
        '',
        user_settings,
        response_format="json",
        system_prompt=system_prompt,
        user_prompt=user_prompt,
    )
    result = _parse_json_response(raw, {})
    classification = (result.get('classification') or 'THREAT').upper()
    if classification not in ('THREAT', 'BUSINESS'):
        classification = 'THREAT'
    return classification


# ---------------------------------------------------------------------------
# 2. BDR schema generation
# ---------------------------------------------------------------------------

def ai_generate_bdr_schema(
    playbook_data: Dict,
    user_settings,
    force_generate: bool = False,
) -> Optional[Dict]:
    """
    Generate BDR schema fields from user input.

    If ``force_generate`` is False the detection type is first classified; if
    it is THREAT-driven None is returned (BDR not applicable).

    Args:
        playbook_data: All workbench fields dict.
        user_settings: UserAISettings instance.
        force_generate: When True, generate BDR regardless of classification.

    Returns:
        BDR schema dict conforming to ShareTide BDR v2.0, or None.
    """
    if not force_generate:
        classification = ai_classify_detection_type(playbook_data, user_settings)
        if classification != 'BUSINESS':
            return None

    system_prompt = (
        "You are a senior compliance and detection architect. "
        "Return only strict JSON that conforms to the requested schema."
    )
    user_prompt = (
        "Generate a Business-Driven Detection Rule (BDR) schema entry for the detection below.\n\n"
        "Output ONLY a single JSON object with these exact keys (no extra keys, no markdown):\n"
        "{\n"
        '  "criticality": "<one of: Emergency|Severe|High|Medium|Low|Baseline - Negligible|Baseline - Minor>",\n'
        '  "domains": ["<subset of: Enterprise|Public Cloud|Private Cloud|Mobile|SaaS|Networking|'
        'OSINT|Embedded|IoT|Industrial>"],\n'
        '  "targets": ["<relevant asset types>"],\n'
        '  "platforms": ["<relevant platforms from: Windows|Linux|macOS|AWS|Azure|GCP|'
        'Active Directory|Azure AD|Office 365|Network Devices>"],\n'
        '  "violation": "<concise policy or compliance violation description>",\n'
        '  "justification": "<compliance framework and article reference>",\n'
        '  "description": "<clear detection objective statement>"\n'
        "}\n\n"
        f"TITLE: {playbook_data.get('title', '')}\n"
        f"GOAL: {playbook_data.get('goal', '')}\n"
        f"TECHNICAL CONTEXT: {playbook_data.get('technical_context', '')}\n"
        f"COMPLIANCE: {playbook_data.get('compliance', '')}\n\n"
        "Return the JSON object only."
    )

    raw = call_ai_provider(
        '',
        user_settings,
        response_format="json",
        system_prompt=system_prompt,
        user_prompt=user_prompt,
    )
    result = _parse_json_response(raw, {})

    # Apply defaults for any missing required fields
    defaults: Dict[str, Any] = {
        'criticality': 'Medium',
        'domains': [],
        'targets': [],
        'platforms': [],
        'violation': '',
        'justification': '',
        'description': playbook_data.get('goal', ''),
    }
    for key, default in defaults.items():
        if key not in result or not result[key]:
            result[key] = default

    return result


# ---------------------------------------------------------------------------
# 3. MDR response enrichment
# ---------------------------------------------------------------------------

def ai_enrich_mdr_response(playbook_data: Dict, user_settings) -> Dict:
    """
    Generate comprehensive MDR response procedures for a detection.

    Args:
        playbook_data: All workbench fields, including response_playbook,
            false_positives, default_severity.
        user_settings: UserAISettings instance.

    Returns:
        Enriched response dict conforming to MDR schema v2.1 response section.
    """
    system_prompt = (
        "You are a senior SOC analyst and incident responder. "
        "Return only strict JSON that conforms to the requested schema."
    )
    user_prompt = (
        "Generate a structured response procedure for the detection use-case below.\n\n"
        "Output ONLY a single JSON object (no markdown) with this exact structure:\n"
        "{\n"
        '  "alert_severity": "<one of: Critical|High|Medium|Low|Informational>",\n'
        '  "responders": "<one of: CSIRC|CATCH|MARTI|S1-SA>",\n'
        '  "procedure": {\n'
        '    "analysis": "<step-by-step triage guide for analysts>",\n'
        '    "searches": [\n'
        '      {\n'
        '        "purpose": "<what this search reveals>",\n'
        '        "system": "<one of: Sentinel|Splunk|Elastic|QRadar|Wazuh>",\n'
        '        "query": "<example query string>"\n'
        '      }\n'
        '    ],\n'
        '    "containment": "<incident containment steps>"\n'
        '  }\n'
        "}\n\n"
        f"TITLE: {playbook_data.get('title', '')}\n"
        f"GOAL: {playbook_data.get('goal', '')}\n"
        f"TECHNICAL CONTEXT: {playbook_data.get('technical_context', '')}\n"
        f"SEVERITY: {playbook_data.get('default_severity', 'MEDIUM')}\n"
        f"FALSE POSITIVES: {playbook_data.get('false_positives', '')}\n"
        f"RESPONSE PLAYBOOK: {playbook_data.get('response_playbook', '')}\n\n"
        "Return the JSON object only."
    )

    raw = call_ai_provider(
        '',
        user_settings,
        response_format="json",
        system_prompt=system_prompt,
        user_prompt=user_prompt,
    )
    result = _parse_json_response(raw, {})

    # Ensure required fields with safe defaults
    severity_raw = (result.get('alert_severity') or playbook_data.get('default_severity') or 'Medium')
    # Normalise case: first letter upper
    severity = severity_raw.capitalize() if severity_raw else 'Medium'
    if severity not in _get_vocab('mdr_alert_severities'):
        severity = 'Medium'

    responders = result.get('responders', 'CSIRC')
    mdr_responders = _get_vocab('mdr_responders')
    if responders not in mdr_responders:
        responders = mdr_responders[0] if mdr_responders else 'CSIRC'

    procedure = result.get('procedure') or {}
    if not isinstance(procedure, dict):
        procedure = {}

    return {
        'alert_severity': severity,
        'responders': responders,
        'procedure': {
            'analysis': procedure.get('analysis', ''),
            'searches': procedure.get('searches', []),
            'containment': procedure.get('containment', ''),
        },
    }


# ---------------------------------------------------------------------------
# 4. Platform and target mapping
# ---------------------------------------------------------------------------

def ai_map_platforms_and_targets(technical_context: str, user_settings) -> Dict:
    """
    Extract platforms, targets and domains from free-text technical context.

    Args:
        technical_context: User's technical description string.
        user_settings: UserAISettings instance.

    Returns:
        Dict with 'platforms', 'targets', and 'domains' lists.
    """
    system_prompt = (
        "You are a detection engineering specialist. "
        "Extract platform/target/domain values and return only strict JSON."
    )
    user_prompt = (
        "Extract the relevant platforms, targets and security domains mentioned or implied "
        "in the technical context below.\n\n"
        "Output ONLY a single JSON object (no markdown):\n"
        "{\n"
        f'  "platforms": ["<subset of: {"|".join(_get_vocab("bdr_platforms") or BDR_PLATFORMS)}>"],\n'
        f'  "targets": ["<subset of: {"|".join(_get_vocab("bdr_targets") or BDR_TARGETS)}>"],\n'
        f'  "domains": ["<subset of: {"|".join(_get_vocab("bdr_domains") or BDR_DOMAINS)}>"]\n'
        "}\n\n"
        "TECHNICAL CONTEXT:\n"
        "<technical_context>\n"
        f"{technical_context}\n"
        "</technical_context>\n\n"
        "Return the JSON object only."
    )

    raw = call_ai_provider(
        '',
        user_settings,
        response_format="json",
        system_prompt=system_prompt,
        user_prompt=user_prompt,
    )
    result = _parse_json_response(raw, {})

    return {
        'platforms': result.get('platforms') if isinstance(result.get('platforms'), list) else [],
        'targets': result.get('targets') if isinstance(result.get('targets'), list) else [],
        'domains': result.get('domains') if isinstance(result.get('domains'), list) else [],
    }


# ---------------------------------------------------------------------------
# 5. Detection Objective Model (DOM) generation
# ---------------------------------------------------------------------------

# Valid logsource values — prefer DB (`dom_log_sources` category); this list is the fallback.
_DOM_VALID_LOGSOURCES_FALLBACK = [
    'siem::Windows Security Events',
    'siem::Sysmon',
    'siem::Network Logs',
    'siem::Process Events',
    'siem::File Events',
    'siem::Registry Events',
    'siem::Authentication Events',
    'siem::Script Execution Events',
    'siem::Generic SIEM',
    'mde::Microsoft Defender XDR',
    'splunk::Splunk',
    'wazuh::Wazuh SIEM',
    'elastic::Elastic SIEM',
    'qradar::QRadar SIEM',
]


def _get_dom_log_sources() -> List[str]:
    """Return DOM-valid log source values from DB, falling back to the built-in list."""
    try:
        from platform_data.models import ShareTideIndexEntry
        values = list(
            ShareTideIndexEntry.objects
            .filter(category='dom_log_sources')
            .order_by('sort_order', 'value')
            .values_list('value', flat=True)
        )
        if values:
            return values
    except Exception:
        pass
    return _DOM_VALID_LOGSOURCES_FALLBACK


# Valid entity values using strict domain::Entity formatting.
_DOM_VALID_ENTITIES = {
    'host::Account',
    'cloud::Account',
    'host::User',
    'cloud::User',
    'host::Hostname',
    'network::IP Address',
    'host::Process',
    'host::Command Line',
}

# Valid methodology values for DOM signals — read from DB (`dom_methodologies` category).
_DOM_VALID_METHODOLOGIES_FALLBACK = {
    'Artifacts', 'Pattern Matching', 'Event Search', 'Statistical',
    'Behavioural', 'Anomaly', 'Machine Learning', 'Heuristic', 'Threat Intelligence',
}


def _get_dom_methodologies() -> set:
    """Return DOM-valid methodology values from DB, falling back to the built-in set."""
    try:
        from platform_data.models import ShareTideIndexEntry
        values = set(
            ShareTideIndexEntry.objects
            .filter(category='dom_methodologies')
            .values_list('value', flat=True)
        )
        if values:
            return values
    except Exception:
        pass
    return _DOM_VALID_METHODOLOGIES_FALLBACK

# Maps legacy/free-form logsource names to schema-compliant tool::name values.
# Keys are lowercase substrings matched against the raw AI-provided value.
# NOTE: MDE/EDR entries must appear before the generic siem:: entries so that
# strings like 'EDR File and Process Telemetry' are matched to MDE first.
_LOGSOURCE_LEGACY_MAP: List[Tuple[List[str], str]] = [
    (['microsoft defender', 'defender for endpoint', 'mde::', ' mde ',
      'edr file', 'edr process', 'edr module', 'edr '], 'mde::Microsoft Defender XDR'),
    (['splunk'], 'splunk::Splunk'),
    (['wazuh'], 'wazuh::Wazuh SIEM'),
    (['elastic'], 'elastic::Elastic SIEM'),
    (['qradar', 'ibm'], 'qradar::QRadar SIEM'),
    (['windows security event', 'security event log', 'winevt', 'evtx',
      'windows event log', 'event log 4'], 'siem::Windows Security Events'),
    (['sysmon'], 'siem::Sysmon'),
    (['network log', 'netflow', 'dns log', 'firewall log', 'proxy log'], 'siem::Network Logs'),
    (['process event', 'process creation', 'process telemetry'], 'siem::Process Events'),
    (['file event', 'file system', 'file creation', 'file modification',
      'file share', 'file auditing', 'file telemetry'], 'siem::File Events'),
    (['registry'], 'siem::Registry Events'),
    (['authentication event', 'logon event', 'kerberos', 'ntlm'], 'siem::Authentication Events'),
    (['script', 'powershell', 'wmi', 'com '], 'siem::Script Execution Events'),
]

# Maps entity name keywords (from AI output or legacy plain names) to valid
# domain::Entity vocabulary values.
_ENTITY_SUFFIX_MAP: Dict[str, str] = {
    # New domain::Entity format
    'account': 'host::Account',
    'cloudaccount': 'cloud::Account',
    'cloud account': 'cloud::Account',
    'clouduser': 'cloud::User',
    'cloud user': 'cloud::User',
    'user': 'host::User',
    'hostname': 'host::Hostname',
    'host': 'host::Hostname',
    'ipaddress': 'network::IP Address',
    'ip address': 'network::IP Address',
    'network': 'network::IP Address',
    'networkconnection': 'network::IP Address',
    'process': 'host::Process',
    'commandline': 'host::Command Line',
    'command line': 'host::Command Line',
    'command_line': 'host::Command Line',
    # Legacy plain-name aliases
    'file': 'host::Process',
    'registrykey': 'host::Hostname',
    'registry': 'host::Hostname',
    'service': 'host::Process',
    'scriptexecution': 'host::Command Line',
    'script': 'host::Command Line',
    'module': 'host::Process',
    'digitalsignature': 'host::Process',
    'tempstorage': 'host::Hostname',
    'connection': 'network::IP Address',
}


def _normalize_logsource(value: str) -> Optional[str]:
    """Map a free-form logsource string to a valid DOM schema logsource value.

    Returns the original value unchanged if it is already valid, applies the
    legacy mapping table for old-style names, or returns None when no mapping
    can be found.  Valid logsources are read from the DB (`dom_log_sources`
    category) on each call so that instance-specific entries injected via
    ``Configurations/schema.toml`` are honoured without code changes.
    """
    valid_logsources = _get_dom_log_sources()
    if value in valid_logsources:
        return value
    lower = value.lower()
    for keywords, mapped in _LOGSOURCE_LEGACY_MAP:
        if any(kw in lower for kw in keywords):
            return mapped
    return None


def _normalize_entity(value: str) -> Optional[str]:
    """Map a free-form entity string to a valid DOM schema entity value.

    Accepts both the new ``domain::Entity`` format (e.g. ``host::Process``) and
    legacy plain names (e.g. ``process``).  Returns None when no valid mapping
    exists.
    """
    if value in _DOM_VALID_ENTITIES:
        return value
    # Try plain lowercase lookup (e.g. 'process' → 'host::Process')
    mapped = _ENTITY_SUFFIX_MAP.get(value.lower())
    if mapped:
        return mapped
    # Handle domain::Entity input: split on '::' and try looking up domain+entity
    # then just the entity segment (e.g. 'host::CommandLine' → suffix 'commandline')
    if '::' in value:
        parts = value.split('::', 1)
        # Try 'domain entity' combined
        combined = f"{parts[0].lower()} {parts[1].lower()}"
        mapped = _ENTITY_SUFFIX_MAP.get(combined)
        if mapped:
            return mapped
        # Try just the entity suffix
        suffix = parts[1].lower()
        mapped = _ENTITY_SUFFIX_MAP.get(suffix)
        if mapped:
            return mapped
    return None


def _normalize_methodology(value: str) -> str:
    """Return a valid DOM schema methodology value.

    Accepts the full OpenTide detection method vocabulary.  Falls back to
    'Behavioural' for unrecognised inputs.
    """
    valid = _get_dom_methodologies()
    if value in valid:
        return value
    # Handle common aliases and spelling variants
    aliases: Dict[str, str] = {
        'behavioral': 'Behavioural',
        'behavior': 'Behavioural',
        'correlation': 'Pattern Matching',
        'threshold': 'Statistical',
        'threat intel': 'Threat Intelligence',
        'ml': 'Machine Learning',
    }
    mapped = aliases.get(value.lower())
    if mapped and mapped in valid:
        return mapped
    return 'Behavioural'


def ai_generate_detection_objective(playbook_data: Dict, user_settings) -> Dict:
    """
    Generate Detection Objective Model (DOM) structure including descriptive signals.

    Signals describe WHAT the detection aims to observe (data sources, observable
    behaviour) but do NOT contain any detection query logic — actual detection
    rules (KQL, SPL, Sigma, WAZUH) must always be provided by the user.

    Args:
        playbook_data: All workbench fields dict.
        user_settings: UserAISettings instance.

    Returns:
        DOM schema dict conforming to DOM Schema v2.1.
    """
    valid_logsources = _get_dom_log_sources()
    valid_methodologies = _get_dom_methodologies()
    _logsource_examples = ' | '.join(valid_logsources[:5]) + (' | ...' if len(valid_logsources) > 5 else '')
    _entity_examples = ' | '.join(sorted(_DOM_VALID_ENTITIES))
    _methodology_examples = ' | '.join(sorted(valid_methodologies))

    system_prompt = (
        "You are a senior detection architect. "
        "Return only strict JSON that conforms to the requested DOM schema."
    )
    user_prompt = (
        "Generate a Detection Objective Model (DOM) for the detection use-case below.\n\n"
        "IMPORTANT: Do NOT generate any detection queries or rule logic. "
        "Signals must only contain descriptive metadata about what data sources and "
        "observable behaviours the detection targets.\n\n"
        "STRICT VOCABULARY RULES — you MUST only use values from the lists below. "
        "Do not invent your own values.\n\n"
        f"METHODOLOGY_VOCAB (detection method): {_methodology_examples}\n"
        f"ENTITY_VOCAB (threat surface, domain::Entity format): {_entity_examples}\n"
        f"LOGSOURCE_VOCAB (log sources, tool::name format): {_logsource_examples}\n\n"
        "Output ONLY a single JSON object (no markdown):\n"
        "{\n"
        '  "priority": "<one of: Critical|High|Medium|Low>",\n'
        '  "type": "Threat",\n'
        '  "description": "<clear detection objective statement>",\n'
        '  "false_positives": "<known false positive scenarios or None>",\n'
        '  "composition": "<atomic|composite>",\n'
        '  "signals": [\n'
        '    {\n'
        '      "id": "sig-001",\n'
        '      "name": "<signal name>",\n'
        '      "description": "<what behaviour or event this signal targets>",\n'
        '      "severity": "<one of: Informational|Low|Medium|High|Critical>",\n'
        '      "data": {\n'
        '        "availability": "<one of: Unknown|Not Available|Partial|Complete>",\n'
        '        "requirements": "<technical details of required data>",\n'
        f'        "logsources": ["<one or more values from LOGSOURCE_VOCAB>"]\n'
        '      },\n'
        f'      "methodology": "<one value from METHODOLOGY_VOCAB>",\n'
        f'      "entities": ["<one or more values from ENTITY_VOCAB>"]\n'
        '    }\n'
        '  ]\n'
        "}\n\n"
        f"TITLE: {playbook_data.get('title', '')}\n"
        f"GOAL: {playbook_data.get('goal', '')}\n"
        f"TECHNICAL CONTEXT: {playbook_data.get('technical_context', '')}\n"
        f"MITRE TECHNIQUE: {playbook_data.get('mitre_technique_id', '')} "
        f"{playbook_data.get('mitre_technique_name', '')}\n"
        f"SEVERITY: {playbook_data.get('default_severity', 'MEDIUM')}\n"
        f"FALSE POSITIVES: {playbook_data.get('false_positives', 'None documented')}\n\n"
        "Return the JSON object only. Do not include any query logic or pseudocode in signals."
    )

    raw = call_ai_provider(
        '',
        user_settings,
        response_format="json",
        system_prompt=system_prompt,
        user_prompt=user_prompt,
    )
    result = _parse_json_response(raw, {})

    priority = result.get('priority', 'Medium')
    if priority not in _get_vocab('dom_priorities'):
        priority = 'Medium'

    # Strip any 'logic' field that the AI may have added despite instructions,
    # ensuring detection rule content never comes from AI.
    signals = result.get('signals', []) if isinstance(result.get('signals'), list) else []
    clean_signals = []
    for sig in signals:
        if isinstance(sig, dict):
            # Support both 'data_source' (legacy) and 'data_sources' (list)
            # Extract to variable for use in logsources
            data_source = sig.get('data_source', '')
            if not data_source:
                legacy = sig.get('data_sources', [])
                data_source = legacy[0] if isinstance(legacy, list) and legacy else ''

            # Build logsources array from data_source or existing logsources,
            # then normalise every entry to a schema-compliant tool::name value.
            raw_logsources = list(sig.get('data', {}).get('logsources', []))
            if data_source and data_source not in raw_logsources:
                raw_logsources.insert(0, data_source)
            normalised_logsources: List[str] = []
            for ls in raw_logsources:
                normalised = _normalize_logsource(ls)
                if normalised and normalised not in normalised_logsources:
                    normalised_logsources.append(normalised)

            # Normalise entities to schema-compliant plain names.
            raw_entities = sig.get('entities', [])
            normalised_entities: List[str] = []
            for ent in (raw_entities if isinstance(raw_entities, list) else []):
                normalised_ent = _normalize_entity(ent)
                if normalised_ent and normalised_ent not in normalised_entities:
                    normalised_entities.append(normalised_ent)

            clean_signals.append({
                'uuid': str(uuid.uuid4()),
                'name': sig.get('name', ''),
                'description': sig.get('description', ''),
                'severity': sig.get('severity', 'Medium'),
                'data': {
                    'availability': sig.get('data', {}).get('availability', 'Unknown'),
                    'requirements': sig.get('data', {}).get('requirements', f'Requires {data_source}'),
                    'logsources': normalised_logsources,
                },
                'methodology': _normalize_methodology(sig.get('methodology', 'Behavioural')),
                'entities': normalised_entities,
            })

    return {
        'priority': priority,
        'type': result.get('type', 'Threat'),
        'description': result.get('description', playbook_data.get('goal', '')),
        'false_positives': result.get('false_positives') or playbook_data.get('false_positives') or '',
        'composition': result.get('composition', 'atomic'),
        'signals': clean_signals,
    }
