# Generated by Django 5.2.7 on 2025-11-09 18:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MitreAttackTechnique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('technique_id', models.CharField(help_text='e.g., T1003.001', max_length=20, unique=True)),
                ('name', models.CharField(help_text='e.g., OS Credential Dumping: LSASS Memory', max_length=255)),
                ('url', models.URLField(max_length=512)),
            ],
            options={
                'ordering': ['technique_id'],
            },
        ),
        migrations.CreateModel(
            name='MitreD3fendTechnique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('d3fend_id', models.CharField(help_text='e.g., D3-SFA', max_length=20, unique=True)),
                ('name', models.CharField(help_text='e.g., System File Analysis', max_length=255)),
                ('url', models.URLField(max_length=512)),
            ],
            options={
                'ordering': ['d3fend_id'],
            },
        ),
        migrations.CreateModel(
            name='MitreEngageTechnique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engage_id', models.CharField(help_text='e.g., E0001', max_length=20, unique=True)),
                ('name', models.CharField(help_text='e.g., Prepare', max_length=255)),
                ('url', models.URLField(max_length=512)),
            ],
            options={
                'ordering': ['engage_id'],
            },
        ),
    ]
