# Generated by Django 5.2.7 on 2025-11-10 16:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MitreIcsTechnique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('technique_id', models.CharField(help_text='e.g., T0801', max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=512)),
            ],
            options={
                'ordering': ['technique_id'],
            },
        ),
        migrations.CreateModel(
            name='MitreMobileTechnique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('technique_id', models.CharField(help_text='e.g., T1401', max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=512)),
            ],
            options={
                'ordering': ['technique_id'],
            },
        ),
    ]
