# Generated by Django 5.2.7 on 2025-11-24 20:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_data', '0002_mitreicstechnique_mitremobiletechnique'),
        ('playbooks', '0013_remove_detectionplaybook_mitre_d3fend_mappings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MitreAnalytic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stix_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('domain', models.CharField(choices=[('enterprise-attack', 'Enterprise'), ('mobile-attack', 'Mobile'), ('ics-attack', 'ICS')], default='enterprise-attack', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MitreDataComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stix_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('domain', models.CharField(choices=[('enterprise-attack', 'Enterprise'), ('mobile-attack', 'Mobile'), ('ics-attack', 'ICS')], default='enterprise-attack', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='MitreD3fendTechnique',
        ),
        migrations.DeleteModel(
            name='MitreEngageTechnique',
        ),
        migrations.AlterModelOptions(
            name='mitreattacktechnique',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mitreicstechnique',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mitremobiletechnique',
            options={},
        ),
        migrations.AddField(
            model_name='mitreattacktechnique',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mitreattacktechnique',
            name='domain',
            field=models.CharField(choices=[('enterprise-attack', 'Enterprise'), ('mobile-attack', 'Mobile'), ('ics-attack', 'ICS')], default='enterprise-attack', max_length=50),
        ),
        migrations.AddField(
            model_name='mitreattacktechnique',
            name='stix_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mitreicstechnique',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mitremobiletechnique',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mitreattacktechnique',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mitreicstechnique',
            name='technique_id',
            field=models.CharField(help_text='e.g., T0800', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='mitremobiletechnique',
            name='technique_id',
            field=models.CharField(help_text='e.g., T1400', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='mitredatacomponent',
            name='techniques',
            field=models.ManyToManyField(blank=True, related_name='data_components', to='platform_data.mitreattacktechnique'),
        ),
        migrations.AddField(
            model_name='mitreanalytic',
            name='data_components',
            field=models.ManyToManyField(blank=True, related_name='analytics', to='platform_data.mitredatacomponent'),
        ),
    ]
