# Generated by Django 5.2.7 on 2025-11-24 21:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_data', '0003_mitreanalytic_mitredatacomponent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MitreDataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stix_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='mitreattacktechnique',
            options={'ordering': ['technique_id']},
        ),
        migrations.RemoveField(
            model_name='mitreanalytic',
            name='data_components',
        ),
        migrations.AddField(
            model_name='mitreanalytic',
            name='data_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics', to='platform_data.mitredatacomponent'),
        ),
        migrations.AlterField(
            model_name='mitredatacomponent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mitredatacomponent',
            name='data_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='platform_data.mitredatasource'),
        ),
    ]
