# Generated by Django 5.2.7 on 2025-11-24 22:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_data', '0004_mitredatasource_alter_mitreattacktechnique_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mitreattacktechnique',
            options={},
        ),
        migrations.RemoveField(
            model_name='mitreanalytic',
            name='data_component',
        ),
        migrations.AlterField(
            model_name='mitreattacktechnique',
            name='technique_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='mitredatacomponent',
            name='stix_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mitredatasource',
            name='stix_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='MitreDetectionStrategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stix_id', models.CharField(max_length=100, unique=True)),
                ('def_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=512, null=True)),
                ('domain', models.CharField(choices=[('enterprise-attack', 'Enterprise'), ('mobile-attack', 'Mobile'), ('ics-attack', 'ICS')], default='enterprise-attack', max_length=50)),
                ('techniques', models.ManyToManyField(blank=True, related_name='detection_strategies', to='platform_data.mitreattacktechnique')),
            ],
        ),
        migrations.AddField(
            model_name='mitreanalytic',
            name='detection_strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics', to='platform_data.mitredetectionstrategy'),
        ),
    ]
