# Generated by Django 5.2.7 on 2025-11-26 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_data', '0005_alter_mitreattacktechnique_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mitredetectionstrategy',
            options={'verbose_name_plural': 'Mitre detection strategies'},
        ),
    ]
