# Generated by Django 5.2.7 on 2026-05-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_data', '0010_attack_v19_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sharetideindexentry',
            name='unique_sharetide_category_value',
        ),
        migrations.AlterField(
            model_name='platformdataversion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='sharetideindexentry',
            unique_together={('category', 'value')},
        ),
    ]
