# Generated by Django 5.2.7 on 2026-06-02 19:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_data', '0011_remove_sharetideindexentry_unique_sharetide_category_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MitreImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(help_text="ATT&CK version to import, e.g. '19.1'", max_length=20)),
                ('mode', models.CharField(choices=[('REMOTE', 'Remote'), ('LOCAL', 'Local')], default='REMOTE', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('log', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mitre_import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MITRE Import Job',
                'verbose_name_plural': 'MITRE Import Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
