# Generated by Django 5.2.7 on 2026-07-01 16:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_data', '0012_mitreimportjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformdataversion',
            name='framework',
            field=models.CharField(
                choices=[
                    ('enterprise-attack', 'MITRE ATT&CK Enterprise'),
                    ('ics-attack', 'MITRE ATT&CK ICS'),
                    ('mobile-attack', 'MITRE ATT&CK Mobile'),
                    ('d3fend', 'MITRE D3FEND'),
                    ('detection-chokepoints', 'Detection Chokepoints'),
                ],
                help_text="Framework identifier (e.g. 'enterprise-attack')",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name='ChokepointSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_repo', models.URLField(default='https://github.com/iimp0ster/detection-chokepoints', help_text='Upstream source repository URL.', max_length=512)),
                ('source_ref', models.CharField(default='main', help_text='Imported ref (branch/tag/commit).', max_length=128)),
                ('source_sha', models.CharField(blank=True, default='', help_text='Resolved upstream commit SHA when available.', max_length=64)),
                ('status', models.CharField(choices=[('STAGED', 'Staged'), ('ACTIVE', 'Active'), ('FAILED', 'Failed'), ('ARCHIVED', 'Archived')], default='STAGED', max_length=16)),
                ('summary', models.JSONField(blank=True, default=dict, help_text='Import summary counters/diff metadata.')),
                ('entry_count', models.PositiveIntegerField(default=0)),
                ('validation_errors', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chokepoint_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chokepoint Snapshot',
                'verbose_name_plural': 'Chokepoint Snapshots',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['status', 'created_at'], name='pld_chkp_snap_st_cr_idx'),
                    models.Index(fields=['source_sha'], name='platform_chkp_snap_sha_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='ChokepointImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_repo', models.URLField(default='https://github.com/iimp0ster/detection-chokepoints', max_length=512)),
                ('source_ref', models.CharField(default='main', max_length=128)),
                ('mode', models.CharField(choices=[('REMOTE', 'Remote'), ('LOCAL', 'Local')], default='REMOTE', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('log', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to='platform_data.chokepointsnapshot')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chokepoint_import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chokepoint Import Job',
                'verbose_name_plural': 'Chokepoint Import Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChokepointEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_key', models.CharField(help_text='Stable key within a snapshot (derived from source path + title/id).', max_length=320)),
                ('source_path', models.CharField(blank=True, default='', max_length=512)),
                ('source_hash', models.CharField(blank=True, default='', max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('primary_technique_id', models.CharField(blank=True, default='', max_length=20)),
                ('sub_technique_id', models.CharField(blank=True, default='', max_length=20)),
                ('technique_name', models.CharField(blank=True, default='', max_length=255)),
                ('tactic', models.CharField(blank=True, default='', max_length=120)),
                ('telemetry_prerequisites', models.TextField(blank=True, default='')),
                ('detection_context', models.TextField(blank=True, default='')),
                ('platforms', models.JSONField(blank=True, default=list)),
                ('data_components', models.JSONField(blank=True, default=list)),
                ('detection_strategy_hints', models.JSONField(blank=True, default=list)),
                ('native_rule_hints', models.JSONField(blank=True, default=dict, help_text="Engine-specific hints, e.g. {'kql': [...], 'spl': [...], 'wazuh_xml': [...]}")),
                ('references', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('confidence', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='UNKNOWN', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='platform_data.chokepointsnapshot')),
            ],
            options={
                'verbose_name': 'Chokepoint Entry',
                'verbose_name_plural': 'Chokepoint Entries',
                'ordering': ['primary_technique_id', 'title'],
                'indexes': [
                    models.Index(fields=['primary_technique_id'], name='platform_chkp_ent_primary_idx'),
                    models.Index(fields=['sub_technique_id'], name='platform_chkp_ent_subtech_idx'),
                    models.Index(fields=['snapshot', 'primary_technique_id'], name='pld_chkp_ent_snap_pr_idx'),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name='chokepointentry',
            constraint=models.UniqueConstraint(fields=('snapshot', 'entry_key'), name='unique_chokepoint_entry_per_snapshot'),
        ),
    ]
