# Generated by Django 5.2.7 on 2025-12-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_alter_rulerepository_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionrule',
            name='format',
            field=models.CharField(choices=[('SIGMA', 'Sigma YAML'), ('KQL', 'Kusto Query Language'), ('WAZUH', 'Wazuh XML'), ('OTHER', 'Other')], default='SIGMA', max_length=10),
        ),
    ]
