# Generated by Django 5.2.7 on 2025-11-18 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('rules', '0003_remove_rulerepository_last_sync_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rulerepository',
            options={'verbose_name_plural': 'Rule Repositories'},
        ),
        migrations.AlterUniqueTogether(
            name='rulerepository',
            unique_together={('organization', 'name')},
        ),
    ]
