# Generated by Django 5.2.7 on 2025-12-09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0007_trigram_indexes'),
        ('rules', '0003_detectionrule_format'),
    ]

    operations = [
        # Merge migration to resolve multiple leaf nodes
    ]
