# Generated by Django 5.2.7 on 2025-12-09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0008_merge_0003_0007'),
        ('playbooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionrule',
            name='playbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_rules', to='playbooks.playbookgraph'),
        ),
    ]
