# Generated by Django 5.2.7 on 2025-12-09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0009_alter_detectionrule_playbook_to_fk'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detectionrule',
            unique_together={('organization', 'playbook', 'format')},
        ),
    ]
