# Generated by Django 5.2.7 on 2025-12-09 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0010_unique_rule_per_format'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detectionrule',
            unique_together=set(),
        ),
    ]
