# Generated by Django 5.2.7 on 2025-12-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0011_alter_detectionrule_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulerepository',
            name='auto_pull_enabled',
            field=models.BooleanField(default=False, help_text='Whether automatic pulls are enabled'),
        ),
        migrations.AddField(
            model_name='rulerepository',
            name='auto_pull_schedule',
            field=models.CharField(choices=[('DISABLED', 'Disabled'), ('24H', 'Every 24 hours'), ('48H', 'Every 48 hours'), ('72H', 'Every 72 hours'), ('WEEKLY', 'Weekly')], default='DISABLED', help_text='Schedule for automatic pulls from this repository', max_length=20),
        ),
        migrations.AddField(
            model_name='rulerepository',
            name='next_scheduled_pull',
            field=models.DateTimeField(blank=True, help_text='When the next scheduled pull should occur', null=True),
        ),
    ]
