# Generated by Django 5.2.7 on 2026-05-29 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_catalog', '0001_initial'),
        ('organizations', '0017_remove_legacy_opentide_models'),
        ('rules', '0017_remove_sigma_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS rules_autocompleteevent (
                            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            format varchar(10) NOT NULL,
                            position integer NOT NULL,
                            suggestions_count integer NOT NULL,
                            data_source_id varchar(100) NULL,
                            context_snapshot text NULL,
                            created_at timestamp with time zone NOT NULL,
                            organization_id bigint NOT NULL,
                            user_id bigint NULL
                        );
                        CREATE INDEX IF NOT EXISTS rules_autocompleteevent_format_962e95b8 ON rules_autocompleteevent (format);
                        CREATE INDEX IF NOT EXISTS rules_autocompleteevent_data_source_id_1da96cc8 ON rules_autocompleteevent (data_source_id);
                    """,
                    reverse_sql="DROP TABLE IF EXISTS rules_autocompleteevent;",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='AutocompleteEvent',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('format', models.CharField(db_index=True, max_length=10)),
                        ('position', models.IntegerField()),
                        ('suggestions_count', models.IntegerField()),
                        ('data_source_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                        ('context_snapshot', models.TextField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autocomplete_events', to='organizations.organization')),
                        ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autocomplete_events', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Autocomplete Event',
                        'verbose_name_plural': 'Autocomplete Events',
                        'ordering': ['-created_at'],
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE rules_fieldmapping
                        DROP CONSTRAINT IF EXISTS unique_field_mapping;
                    """,
                    reverse_sql="""
                        ALTER TABLE rules_fieldmapping
                        ADD CONSTRAINT unique_field_mapping
                        UNIQUE (data_source_id, sigma_field, kql_field);
                    """,
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='fieldmapping',
                    name='unique_field_mapping',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE rules_kqlfield
                        DROP CONSTRAINT IF EXISTS unique_kql_table_field;
                    """,
                    reverse_sql="""
                        ALTER TABLE rules_kqlfield
                        ADD CONSTRAINT unique_kql_table_field
                        UNIQUE (table_id, field_name);
                    """,
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='kqlfield',
                    name='unique_kql_table_field',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF NOT EXISTS (
                                SELECT 1 FROM pg_constraint
                                WHERE conrelid = 'rules_fieldmapping'::regclass
                                  AND contype = 'u'
                                  AND pg_get_constraintdef(oid) ILIKE 'UNIQUE (data_source_id, sigma_field, kql_field)%'
                            ) THEN
                                ALTER TABLE rules_fieldmapping
                                ADD CONSTRAINT rules_fieldmapping_data_source_id_sigma_fie_b70ed711_uniq
                                UNIQUE (data_source_id, sigma_field, kql_field);
                            END IF;
                        END$$;
                    """,
                    reverse_sql="""
                        DO $$
                        DECLARE
                            existing_name text;
                        BEGIN
                            SELECT conname INTO existing_name
                            FROM pg_constraint
                            WHERE conrelid = 'rules_fieldmapping'::regclass
                              AND contype = 'u'
                              AND pg_get_constraintdef(oid) ILIKE 'UNIQUE (data_source_id, sigma_field, kql_field)%';
                            IF existing_name IS NOT NULL THEN
                                EXECUTE format('ALTER TABLE rules_fieldmapping DROP CONSTRAINT %I', existing_name);
                            END IF;
                        END$$;
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='fieldmapping',
                    unique_together={('data_source', 'sigma_field', 'kql_field')},
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF NOT EXISTS (
                                SELECT 1 FROM pg_constraint
                                WHERE conrelid = 'rules_kqlfield'::regclass
                                  AND contype = 'u'
                                  AND pg_get_constraintdef(oid) ILIKE 'UNIQUE (table_id, field_name)%'
                            ) THEN
                                ALTER TABLE rules_kqlfield
                                ADD CONSTRAINT rules_kqlfield_table_id_field_name_uniq
                                UNIQUE (table_id, field_name);
                            END IF;
                        END$$;
                    """,
                    reverse_sql="""
                        DO $$
                        DECLARE
                            existing_name text;
                        BEGIN
                            SELECT conname INTO existing_name
                            FROM pg_constraint
                            WHERE conrelid = 'rules_kqlfield'::regclass
                              AND contype = 'u'
                              AND pg_get_constraintdef(oid) ILIKE 'UNIQUE (table_id, field_name)%';
                            IF existing_name IS NOT NULL THEN
                                EXECUTE format('ALTER TABLE rules_kqlfield DROP CONSTRAINT %I', existing_name);
                            END IF;
                        END$$;
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='kqlfield',
                    unique_together={('table', 'field_name')},
                ),
            ],
        ),
    ]
