# Generated by Django 5.2.7 on 2025-11-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_catalog', '0001_initial'),
        ('playbooks', '0002_initial'),
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionplaybook',
            name='detection_rules',
            field=models.ManyToManyField(blank=True, related_name='playbooks', to='rules.detectionrule'),
        ),
        migrations.AddField(
            model_name='detectionplaybook',
            name='required_data_sources',
            field=models.ManyToManyField(blank=True, related_name='playbooks', to='data_catalog.datasource'),
        ),
    ]
