# Generated by Django 5.2.7 on 2025-11-10 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_data', '0002_mitreicstechnique_mitremobiletechnique'),
        ('playbooks', '0003_detectionplaybook_detection_rules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionplaybook',
            name='analytic_id',
            field=models.CharField(blank=True, help_text='Unique ID for the analytic (e.g., DE-2025-001)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detectionplaybook',
            name='data_source_robustness',
            field=models.CharField(blank=True, choices=[('A', 'Application (A)'), ('U', 'User-Mode (U)'), ('K', 'Kernel-Mode (K)'), ('P', 'Protocol Payload (P)'), ('H', 'Protocol Header (H)'), ('N', 'N/A')], help_text='Where does the data come from? (e.g., K for Kernel-Mode)', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='detectionplaybook',
            name='exclusion_strategy',
            field=models.TextField(blank=True, help_text='Surgically precise exclusions (e.g., trusted signers)', null=True),
        ),
        migrations.AddField(
            model_name='detectionplaybook',
            name='false_positive_rate',
            field=models.IntegerField(blank=True, help_text='Estimated FP rate on a 0-100% scale (for DETECTION playbooks)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='detectionplaybook',
            name='hypothesis',
            field=models.TextField(blank=True, help_text='The testable question this hunt is designed to answer (for HUNT playbooks)', null=True),
        ),
        migrations.AddField(
            model_name='detectionplaybook',
            name='known_false_positives',
            field=models.TextField(blank=True, help_text='Known benign triggers to reduce noise (for DETECTION playbooks)', null=True),
        ),
        migrations.AddField(
            model_name='detectionplaybook',
            name='mitre_attack_mappings',
            field=models.ManyToManyField(blank=True, related_name='playbooks', to='platform_data.mitreattacktechnique'),
        ),
        migrations.AddField(
            model_name='detectionplaybook',
            name='mitre_d3fend_mappings',
            field=models.ManyToManyField(blank=True, related_name='playbooks', to='platform_data.mitred3fendtechnique'),
        ),
        migrations.AddField(
            model_name='detectionplaybook',
            name='mitre_engage_mappings',
            field=models.ManyToManyField(blank=True, related_name='playbooks', to='platform_data.mitreengagetechnique'),
        ),
        migrations.AddField(
            model_name='detectionplaybook',
            name='mitre_ics_mappings',
            field=models.ManyToManyField(blank=True, related_name='playbooks', to='platform_data.mitreicstechnique'),
        ),
        migrations.AddField(
            model_name='detectionplaybook',
            name='mitre_mobile_mappings',
            field=models.ManyToManyField(blank=True, related_name='playbooks', to='platform_data.mitremobiletechnique'),
        ),
        migrations.AddField(
            model_name='detectionplaybook',
            name='robustness_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Level 1: Ephemeral (IP, Domain, Hash)'), (2, 'Level 2: Core to Adversary-Brought Tool'), (3, 'Level 3: Core to Pre-Existing Tool (LOLBin)'), (4, 'Level 4: Core to Some Implementations'), (5, 'Level 5: Core to Technique (Invariant)')], help_text='How easy is this detection to evade?', null=True),
        ),
        migrations.AddField(
            model_name='detectionplaybook',
            name='soar_containment',
            field=models.TextField(blank=True, help_text='Automated containment steps (e.g., Isolate-Host)', null=True),
        ),
        migrations.AddField(
            model_name='detectionplaybook',
            name='soar_enrichment',
            field=models.TextField(blank=True, help_text='Automated enrichment steps (e.g., Get-UserDetails)', null=True),
        ),
        migrations.AddField(
            model_name='detectionplaybook',
            name='soar_triage',
            field=models.TextField(blank=True, help_text='Automated triage logic (e.g., IF user.is_vip -> THEN set_severity=High)', null=True),
        ),
        migrations.AddField(
            model_name='detectionplaybook',
            name='testing_procedures',
            field=models.TextField(blank=True, help_text='Test cases and synonym tools to validate the detection', null=True),
        ),
        migrations.AddField(
            model_name='detectionplaybook',
            name='triage_guidance',
            field=models.TextField(blank=True, help_text='Step-by-step instructions for T1 analysts (for DETECTION playbooks)', null=True),
        ),
        migrations.AddField(
            model_name='detectionplaybook',
            name='version',
            field=models.CharField(default='1.0', help_text='Semantic version of the analytic (e.g., 1.0)', max_length=10),
        ),
    ]
