# Generated by Django 5.2.7 on 2025-11-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0004_detectionplaybook_analytic_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionplaybook',
            name='execution_modalities',
            field=models.TextField(blank=True, help_text='Execution modalities or behavioral variants addressed', null=True),
        ),
        migrations.AddField(
            model_name='detectionplaybook',
            name='function_call_graphs',
            field=models.TextField(blank=True, help_text='Relevant function/API call graph abstractions', null=True),
        ),
        migrations.AddField(
            model_name='detectionplaybook',
            name='operational_path',
            field=models.TextField(blank=True, help_text='High-level operational path / phases for this detection/hunt', null=True),
        ),
    ]
