# Generated by Django 5.2.7 on 2025-11-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0005_detectionplaybook_execution_modalities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionplaybook',
            name='status',
            field=models.CharField(choices=[('IDEA', 'Idea/Hypothesis'), ('RESEARCH', 'In Research'), ('DEVELOPMENT', 'In Development'), ('REVIEW', 'Peer Review'), ('APPROVED', 'Approved'), ('TESTING', 'Testing/Validation'), ('DEPLOYED', 'Deployed'), ('TUNING', 'Tuning/Maintenance')], default='IDEA', max_length=20),
        ),
    ]
