# Generated by Django 5.2.7 on 2025-11-18 07:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('platform_data', '0002_mitreicstechnique_mitremobiletechnique'),
        ('playbooks', '0006_alter_detectionplaybook_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionplaybook',
            name='mitre_attack_mappings',
        ),
        migrations.RemoveField(
            model_name='detectionplaybook',
            name='mitre_d3fend_mappings',
        ),
        migrations.RemoveField(
            model_name='detectionplaybook',
            name='mitre_engage_mappings',
        ),
        migrations.CreateModel(
            name='PlaybookGraph',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('IDEA', 'Idea/Hypothesis'), ('RESEARCH', 'In Research'), ('DEVELOPMENT', 'In Development'), ('REVIEW', 'Peer Review'), ('APPROVED', 'Approved'), ('TESTING', 'Testing/Validation'), ('DEPLOYED', 'Deployed'), ('TUNING', 'Tuning/Maintenance')], default='IDEA', max_length=20)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_graphs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbook_graphs', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PlaybookNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('layer_name', models.CharField(default='New Node', max_length=100)),
                ('position_x', models.FloatField(default=50)),
                ('position_y', models.FloatField(default=50)),
                ('goal', models.TextField(blank=True, null=True)),
                ('categorization', models.JSONField(blank=True, default=dict)),
                ('strategy_abstract', models.TextField(blank=True, null=True)),
                ('technical_context', models.TextField(blank=True, null=True)),
                ('blind_spots', models.TextField(blank=True, null=True)),
                ('false_positives', models.TextField(blank=True, null=True)),
                ('validation', models.JSONField(blank=True, default=dict)),
                ('priority', models.CharField(default='Medium', max_length=10)),
                ('response', models.TextField(blank=True, null=True)),
                ('detection_rule', models.JSONField(blank=True, default=dict)),
                ('acd_elements', models.JSONField(blank=True, default=list)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='playbooks.playbookgraph')),
                ('mitre_attack_mappings', models.ManyToManyField(blank=True, related_name='playbook_nodes', to='platform_data.mitreattacktechnique')),
            ],
        ),
        migrations.CreateModel(
            name='PlaybookEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='playbooks.playbookgraph')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_edges', to='playbooks.playbooknode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_edges', to='playbooks.playbooknode')),
            ],
        ),
    ]
