# Generated by Django 5.2.7 on 2025-11-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0007_remove_detectionplaybook_mitre_attack_mappings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playbooknode',
            name='acd_elements',
        ),
        migrations.RemoveField(
            model_name='playbooknode',
            name='blind_spots',
        ),
        migrations.RemoveField(
            model_name='playbooknode',
            name='categorization',
        ),
        migrations.RemoveField(
            model_name='playbooknode',
            name='detection_rule',
        ),
        migrations.RemoveField(
            model_name='playbooknode',
            name='false_positives',
        ),
        migrations.RemoveField(
            model_name='playbooknode',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='playbooknode',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='playbooknode',
            name='response',
        ),
        migrations.RemoveField(
            model_name='playbooknode',
            name='strategy_abstract',
        ),
        migrations.RemoveField(
            model_name='playbooknode',
            name='technical_context',
        ),
        migrations.RemoveField(
            model_name='playbooknode',
            name='validation',
        ),
        migrations.AddField(
            model_name='playbooknode',
            name='template_data',
            field=models.JSONField(blank=True, default=dict, help_text='The full dcg420 detection template for this node.'),
        ),
    ]
