# Generated by Django 5.2.7 on 2025-11-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0008_remove_playbooknode_acd_elements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionplaybook',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='If true, this playbook is visible as a read-only template to all orgs in the same Entity.'),
        ),
    ]
