# Generated by Django 5.2.7 on 2025-11-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0009_detectionplaybook_is_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookgraph',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playbookgraph',
            name='playbooks',
            field=models.ManyToManyField(blank=True, help_text='Detection playbooks that this abstraction capability graph is attached to.', related_name='graphs', to='playbooks.detectionplaybook'),
        ),
        migrations.AddField(
            model_name='playbookgraph',
            name='png_snapshot',
            field=models.ImageField(blank=True, help_text='Rendered PNG snapshot of this graph canvas.', null=True, upload_to='playbook_graphs/'),
        ),
    ]
