# Generated by Django 5.2.7 on 2025-11-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_data', '0002_mitreicstechnique_mitremobiletechnique'),
        ('playbooks', '0010_playbookgraph_notes_playbookgraph_playbooks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionplaybook',
            name='mitre_attack_mappings',
            field=models.ManyToManyField(blank=True, related_name='playbooks', to='platform_data.mitreattacktechnique'),
        ),
        migrations.AddField(
            model_name='detectionplaybook',
            name='mitre_d3fend_mappings',
            field=models.ManyToManyField(blank=True, related_name='playbooks', to='platform_data.mitred3fendtechnique'),
        ),
        migrations.AddField(
            model_name='detectionplaybook',
            name='mitre_engage_mappings',
            field=models.ManyToManyField(blank=True, related_name='playbooks', to='platform_data.mitreengagetechnique'),
        ),
    ]
