# Generated by Django 5.2.7 on 2025-11-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0011_detectionplaybook_mitre_attack_mappings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionplaybook',
            name='technical_details',
            field=models.TextField(blank=True, help_text='Deep technical implementation notes (for HUNT playbooks)', null=True),
        ),
    ]
