# Generated by Django 5.2.7 on 2025-11-24 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0012_detectionplaybook_technical_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionplaybook',
            name='mitre_d3fend_mappings',
        ),
        migrations.RemoveField(
            model_name='detectionplaybook',
            name='mitre_engage_mappings',
        ),
    ]
