# Generated by Django 5.2.7 on 2025-11-26 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_entity'),
        ('platform_data', '0006_alter_mitredetectionstrategy_options'),
        ('playbooks', '0014_playbookgraph_tags_alter_task_playbook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playbooknode',
            name='mitre_attack_mappings',
        ),
        migrations.RemoveField(
            model_name='playbooknode',
            name='template_data',
        ),
        migrations.AddField(
            model_name='playbookgraph',
            name='blind_spots',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='playbookgraph',
            name='detection_rule',
            field=models.TextField(blank=True, help_text='Raw Sigma/Logic'),
        ),
        migrations.AddField(
            model_name='playbookgraph',
            name='false_positives',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='playbookgraph',
            name='goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='playbookgraph',
            name='mitre_technique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_data.mitreattacktechnique'),
        ),
        migrations.AddField(
            model_name='playbookgraph',
            name='response_playbook',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='playbookgraph',
            name='selected_strategy',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='playbookgraph',
            name='technical_context',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='playbookgraph',
            name='triage_guidance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='playbooknode',
            name='ui_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='playbookgraph',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playbookgraph',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='playbookgraph',
            name='playbooks',
            field=models.ManyToManyField(blank=True, related_name='graphs', to='playbooks.detectionplaybook'),
        ),
        migrations.AlterField(
            model_name='playbookgraph',
            name='png_snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='playbook_graphs/'),
        ),
        migrations.AlterField(
            model_name='playbookgraph',
            name='status',
            field=models.CharField(default='IDEA', max_length=20),
        ),
    ]
