# Generated by Django 5.2.7 on 2025-11-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0015_remove_playbooknode_mitre_attack_mappings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookgraph',
            name='git_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SYNCED', 'Synced'), ('MODIFIED', 'Modified')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='playbookgraph',
            name='last_commit_hash',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='playbookgraph',
            name='target_file_path',
            field=models.CharField(blank=True, help_text='e.g. rules/windows/process_creation/proc_mimikatz.yml', max_length=512),
        ),
    ]
