# Generated by Django 5.2.7 on 2025-11-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0016_playbookgraph_git_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbooknode',
            name='color',
            field=models.CharField(default='default', help_text='Node color: default, blue, green, yellow, red', max_length=20),
        ),
    ]
