# Generated by Django 5.2.7 on 2025-11-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0017_playbooknode_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookgraph',
            name='custom_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='playbookgraph',
            name='data_source_robustness',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='playbookgraph',
            name='robustness_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playbookgraph',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
