# Generated by Django 5.2.7 on 2025-11-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0018_playbookgraph_custom_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbookgraph',
            name='data_source_robustness',
            field=models.CharField(blank=True, choices=[('K', 'Kernel-Mode (K)'), ('U', 'User-Mode (U)'), ('A', 'Application (A)'), ('H', 'Protocol Header (H)'), ('P', 'Protocol Payload (P)')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='playbookgraph',
            name='robustness_level',
            field=models.IntegerField(default=0, help_text='1=Ephemeral, 2=Tool, 3=LOLBin, 4=Behavior, 5=Invariant'),
        ),
    ]
