# Generated by Django 5.2.7 on 2025-11-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0019_alter_playbookgraph_data_source_robustness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookgraph',
            name='alert_trigger',
            field=models.TextField(blank=True, default='Triggered when the Detection Logic condition is met.'),
        ),
        migrations.AddField(
            model_name='playbookgraph',
            name='containment_steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='playbookgraph',
            name='default_severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='playbookgraph',
            name='enrichment_steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='playbookgraph',
            name='notification_steps',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
