# Generated by Django 5.2.7 on 2025-12-08 22:26

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_data', '0006_alter_mitredetectionstrategy_options'),
        ('playbooks', '0027_merge_test_fields'),
        ('tags', '0005_alter_taggedgraph_id_alter_taggedgraph_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbooknode',
            name='mitre_attack_mappings',
            field=models.ManyToManyField(blank=True, related_name='nodes', to='platform_data.mitreattacktechnique'),
        ),
        migrations.AlterField(
            model_name='playbookgraph',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='tags.TaggedGraph', to='tags.TenantTag', verbose_name='Tags'),
        ),
    ]
