# Generated by Django 5.2.7 on 2026-04-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0035_opentidepreviewtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookgraph',
            name='internal_references',
            field=models.JSONField(blank=True, default=list, help_text='Internal references (tickets, case IDs, internal docs)'),
        ),
        migrations.AddField(
            model_name='playbookgraph',
            name='public_references',
            field=models.JSONField(blank=True, default=list, help_text='Public references (URLs, research papers, blog posts)'),
        ),
        migrations.AddField(
            model_name='playbookgraph',
            name='threat_actors',
            field=models.JSONField(blank=True, default=list, help_text='Known threat actors using this TTP (structured data)'),
        ),
        migrations.AddField(
            model_name='playbookgraph',
            name='tlp_classification',
            field=models.CharField(choices=[('CLEAR', 'TLP:CLEAR - Public disclosure'), ('GREEN', 'TLP:GREEN - Community sharing'), ('AMBER', 'TLP:AMBER - Limited disclosure'), ('AMBER+STRICT', 'TLP:AMBER+STRICT - Organization only'), ('RED', 'TLP:RED - Personal for named recipients')], default='AMBER', help_text='Traffic Light Protocol classification for information sharing', max_length=20),
        ),
    ]
