# Generated by Django 5.2.7 on 2026-05-11 10:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_capability_abstractions(apps, schema_editor):
    MitreAttackTechnique = apps.get_model('platform_data', 'MitreAttackTechnique')
    CapabilityAbstraction = apps.get_model('playbooks', 'CapabilityAbstraction')

    technique = MitreAttackTechnique.objects.filter(technique_id='T1218.005').first()
    if technique is None:
        return

    entries = [
        {
            'abstraction_layer': 'TOOL',
            'component_artifact': 'mshta.exe',
            'adversary_purpose': 'Launch HTA content or scriptable remote payloads through a signed Microsoft binary.',
            'common_evasions': 'Renamed HTA content, indirect invocation through script engines, or shifting to behavior that outlives the initial binary execution.',
            'expected_observables': 'mshta.exe process creation, command-line URL/file parameters, parent-child execution chains.',
            'applicable_telemetry': 'Process creation, command-line auditing, image load telemetry, parent-child lineage.',
            'detection_value': 'Fast quick-win anchor for signed binary proxy execution, but relatively easy to evade if the binary is swapped or invocation path changes.',
            'robustness_level': 2,
        },
        {
            'abstraction_layer': 'API_EXPORT',
            'component_artifact': 'mshta script engine / COM invocation flow',
            'adversary_purpose': 'Invoke script execution semantics behind the signed binary rather than keying only on the process name.',
            'common_evasions': 'Alternative script hosts, indirect COM activation, staged execution through benign launcher chains.',
            'expected_observables': 'Script engine activation, suspicious COM usage, API invocation sequences associated with HTA/script execution.',
            'applicable_telemetry': 'API/ETW tracing, COM instrumentation, enriched EDR behavior telemetry.',
            'detection_value': 'More resilient than binary-only detection because it tracks the execution behavior underneath the launcher.',
            'robustness_level': 4,
        },
        {
            'abstraction_layer': 'REGISTRY_OBJECT',
            'component_artifact': 'HTA / protocol handler registration abuse',
            'adversary_purpose': 'Persist or redirect execution through registry-backed handler changes that abuse Mshta semantics.',
            'common_evasions': 'Temporary handler changes, per-user registration, cleanup after execution.',
            'expected_observables': 'Registry writes to protocol handlers, shell open command changes, suspicious handler targets pointing to mshta or script content.',
            'applicable_telemetry': 'Registry auditing, autoruns/persistence telemetry, config drift monitoring.',
            'detection_value': 'Useful corroborating detection for setup and persistence workflows that support the primary execution path.',
            'robustness_level': 3,
        },
        {
            'abstraction_layer': 'NETWORK_BEHAVIOR',
            'component_artifact': 'remote script retrieval over HTTP(S)',
            'adversary_purpose': 'Fetch remote HTA or script content used to bootstrap malicious execution.',
            'common_evasions': 'TLS encryption, short-lived infrastructure, proxy relays, staging through CDN-like domains.',
            'expected_observables': 'Outbound connections from mshta or follow-on processes to remote script hosting infrastructure.',
            'applicable_telemetry': 'Network connections, DNS, proxy logs, URL telemetry, process-network correlation.',
            'detection_value': 'Strong corroborating signal when paired with process or behavior detections; valuable for correlation and validation.',
            'robustness_level': 4,
        },
    ]

    for entry in entries:
        CapabilityAbstraction.objects.get_or_create(
            technique=technique,
            organization=None,
            abstraction_layer=entry['abstraction_layer'],
            component_artifact=entry['component_artifact'],
            defaults={
                **entry,
                'source_kind': 'SEEDED',
                'review_status': 'APPROVED',
                'is_baseline': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_opentide_hef_publish'),
        ('platform_data', '0010_attack_v19_fields'),
        ('playbooks', '0037_add_threat_surface'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookgraph',
            name='detection_focus_layer',
            field=models.CharField(blank=True, choices=[('TOOL', 'Tool / Binary'), ('API_EXPORT', 'API / Export'), ('COM_IPC', 'COM / IPC'), ('REGISTRY_OBJECT', 'Registry Object'), ('PROTOCOL', 'Protocol'), ('PROCESS_BEHAVIOR', 'Process Behavior'), ('NETWORK_BEHAVIOR', 'Network Behavior')], default='', help_text='The capability abstraction layer the engineer wants AI generation to prioritize.', max_length=32),
        ),
        migrations.CreateModel(
            name='CapabilityAbstraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('abstraction_layer', models.CharField(choices=[('TOOL', 'Tool / Binary'), ('API_EXPORT', 'API / Export'), ('COM_IPC', 'COM / IPC'), ('REGISTRY_OBJECT', 'Registry Object'), ('PROTOCOL', 'Protocol'), ('PROCESS_BEHAVIOR', 'Process Behavior'), ('NETWORK_BEHAVIOR', 'Network Behavior')], max_length=32)),
                ('component_artifact', models.CharField(max_length=255)),
                ('adversary_purpose', models.TextField(blank=True)),
                ('common_evasions', models.TextField(blank=True)),
                ('expected_observables', models.TextField(blank=True)),
                ('applicable_telemetry', models.TextField(blank=True)),
                ('detection_value', models.TextField(blank=True)),
                ('robustness_level', models.IntegerField(default=0, help_text='Suggested robustness tradeoff for this abstraction (1-5, aligned to the workbench badge scale).')),
                ('source_kind', models.CharField(choices=[('SEEDED', 'Seeded Baseline'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=16)),
                ('review_status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=16)),
                ('is_baseline', models.BooleanField(default=False, help_text='True when this entry is part of the shared seeded baseline library.')),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_capability_abstractions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='Null means this is a shared baseline entry available to all organizations.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capability_abstractions', to='organizations.organization')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_abstractions', to='platform_data.mitreattacktechnique')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_capability_abstractions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['technique__technique_id', 'abstraction_layer', 'component_artifact'],
            },
        ),
        migrations.AddField(
            model_name='playbookgraph',
            name='selected_capability_abstractions',
            field=models.ManyToManyField(blank=True, help_text='Capability abstractions selected as grounding knowledge for this workbench.', related_name='playbook_graphs', to='playbooks.capabilityabstraction'),
        ),
        migrations.AddConstraint(
            model_name='capabilityabstraction',
            constraint=models.UniqueConstraint(fields=('technique', 'organization', 'abstraction_layer', 'component_artifact'), name='unique_capability_abstraction_per_scope'),
        ),
        migrations.RunPython(seed_capability_abstractions, migrations.RunPython.noop),
    ]
