# Generated by Django 5.2.7 on 2026-06-11 00:00

from django.db import migrations, models
from django.db.models import Q


def init_counter_and_backfill_missing_ids(apps, schema_editor):
    PlaybookGraph = apps.get_model('playbooks', 'PlaybookGraph')
    WorkbenchIdCounter = apps.get_model('playbooks', 'WorkbenchIdCounter')
    db_alias = schema_editor.connection.alias

    max_numeric_id = 0
    existing_ids = (
        PlaybookGraph.objects.using(db_alias)
        .exclude(custom_id__isnull=True)
        .values_list('custom_id', flat=True)
    )
    for custom_id in existing_ids:
        value = (custom_id or '').strip()
        if len(value) == 8 and value.startswith('DE') and value[2:].isdigit():
            max_numeric_id = max(max_numeric_id, int(value[2:]))

    counter_start = max_numeric_id + 1 if max_numeric_id else 1
    counter, _ = WorkbenchIdCounter.objects.using(db_alias).get_or_create(
        singleton_key=1,
        defaults={'next_value': counter_start},
    )
    if counter.next_value < counter_start:
        counter.next_value = counter_start
        counter.save(update_fields=['next_value', 'updated_at'])

    next_value = counter.next_value
    missing_graphs = (
        PlaybookGraph.objects.using(db_alias)
        .filter(Q(custom_id__isnull=True) | Q(custom_id=''))
        .order_by('created_at', 'id')
    )
    for graph in missing_graphs.iterator():
        graph.custom_id = f"DE{next_value:06d}"
        graph.save(update_fields=['custom_id'])
        next_value += 1

    if next_value != counter.next_value:
        counter.next_value = next_value
        counter.save(update_fields=['next_value', 'updated_at'])


def noop_reverse(apps, schema_editor):
    # Keep assigned IDs stable on rollback.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0041_l1portalentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkbenchIdCounter',
            fields=[
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('next_value', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workbench ID Counter',
                'verbose_name_plural': 'Workbench ID Counter',
            },
        ),
        migrations.RunPython(init_counter_and_backfill_missing_ids, noop_reverse),
    ]
