# Generated by Django 5.2.7 on 2026-06-04 00:00

import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Short descriptive title', max_length=255)),
                ('description', models.TextField(help_text='What this prompt does')),
                ('category', models.CharField(choices=[('ANALYTICS', 'Analytics & Insights'), ('THREAT_HUNTING', 'Threat Hunting'), ('COMPLIANCE', 'Compliance & Reporting'), ('OPERATIONS', 'Operational Efficiency')], default='ANALYTICS', max_length=50)),
                ('prompt_template', models.TextField(help_text='Jinja2 template for the AI prompt. Use {{variables}} for dynamic context.')),
                ('is_system', models.BooleanField(default=True, help_text='System prompts are pre-loaded and cannot be deleted by users')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive prompts are hidden from UI')),
                ('required_role', models.CharField(choices=[('ADMIN', 'Admin Only'), ('REVIEWER', 'Reviewer and Above')], default='REVIEWER', help_text='Minimum role required to execute this prompt', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Display order within category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='updated_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Prompt',
                'verbose_name_plural': 'AI Prompts',
                'ordering': ['category', 'order', 'title'],
            },
        ),
    ]
