# Generated by Django 5.2.7 on 2026-06-04 19:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt_reports', '0002_seed_ai_prompts'),
        ('organizations', '0021_dac_mode_deploy_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportMailingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_subscribed', models.BooleanField(default=True, help_text='Whether the user is currently on the mailing list')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_list_members', to='organizations.organization')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_mailing_entries', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_mailing_entry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Mailing List Entry',
                'verbose_name_plural': 'Report Mailing List',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReportSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('stats_json', models.JSONField(help_text='Full statistics payload for this month')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_snapshots', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Monthly Report Snapshot',
                'verbose_name_plural': 'Monthly Report Snapshots',
                'ordering': ['year', 'month'],
                'unique_together': {('organization', 'year', 'month')},
            },
        ),
    ]
