# Generated by Django 5.2.7 on 2025-11-12

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    # No-op placeholder to avoid duplicate table creation; real table was created in 0002_taggedk-article
    operations = []
