# Generated by Django 5.2.7 on 2025-11-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tenanttag_name_alter_tenanttag_slug'),
        ('tags', '0002_tagged_kb_article'),
        ('tags', '0002_taggedk-article'),
    ]

    operations = [
    ]
