# Generated by Django on 2025-11-28
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0025_merge_conflict_false_positive_rate'),
        ('tags', '0003_merge_20251112_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_taggedgraph_items', to='tags.tenanttag')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playbooks.playbookgraph')),
            ],
            options={
                'unique_together': {('content_object', 'tag')},
            },
        ),
    ]
