# Generated by Django 5.2.7 on 2025-12-08 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_taggedgraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggedgraph',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taggedgraph',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tags.tenanttag'),
        ),
    ]
