# Generated by Django 5.2.7 on 2025-11-11 17:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('playbooks', '0005_detectionplaybook_execution_modalities_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('APPROVED', 'Approved'), ('CHANGES_REQUESTED', 'Changes Requested'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='The user who requested the review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_review_requests', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='organizations.organization')),
                ('playbook', models.ForeignKey(help_text='The playbook being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='playbooks.detectionplaybook')),
                ('reviewers', models.ManyToManyField(help_text='Users assigned to perform the review', related_name='review_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='The user who wrote the comment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_comments', to=settings.AUTH_USER_MODEL)),
                ('review_request', models.ForeignKey(help_text='The review request this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='review.reviewrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
