# Generated by Django 5.2.7 on 2025-12-23 11:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Optional title for the news post', max_length=200)),
                ('content', models.TextField(help_text='News content (supports Markdown, max 500 chars)', max_length=500)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', help_text='Priority level of the announcement', max_length=10)),
                ('category', models.CharField(choices=[('UPDATE', '🔄 Platform Update'), ('OUTAGE', '⚠️ Planned Outage'), ('FEATURE', '🚀 New Feature'), ('MAINTENANCE', '🔧 Maintenance'), ('ANNOUNCEMENT', '📢 General Announcement'), ('SECURITY', '🔒 Security Advisory')], default='ANNOUNCEMENT', help_text='Category with emoji icon', max_length=20)),
                ('is_published', models.BooleanField(default=False, help_text='Whether this post is visible to users')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned posts appear at the top')),
                ('published_at', models.DateTimeField(blank=True, help_text='When the post was published', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Post will auto-hide after this date (default: 180 days from publish)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNewsRead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('news_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by_users', to='news.newspost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_news', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User News Read Status',
                'verbose_name_plural': 'User News Read Statuses',
            },
        ),
        migrations.AddIndex(
            model_name='newspost',
            index=models.Index(fields=['is_published', 'expires_at'], name='news_newspo_is_publ_8bb2d3_idx'),
        ),
        migrations.AddIndex(
            model_name='newspost',
            index=models.Index(fields=['published_at'], name='news_newspo_publish_406864_idx'),
        ),
        migrations.AddIndex(
            model_name='usernewsread',
            index=models.Index(fields=['user', 'read_at'], name='news_userne_user_id_a2c20a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usernewsread',
            unique_together={('user', 'news_post')},
        ),
    ]
