# Generated by Django 5.2.7 on 2026-05-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSettings',
            fields=[
                ('id', models.PositiveIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('digest_enabled', models.BooleanField(default=True)),
                ('digest_day', models.CharField(default='MONDAY', help_text='Day of week for digest (MONDAY..SUNDAY)', max_length=10)),
                ('digest_hour', models.PositiveSmallIntegerField(default=8, help_text='Hour (UTC) to send digest (0-23)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Settings',
                'verbose_name_plural': 'News Settings',
            },
        ),
    ]
