# Generated by Django 5.2.7 on 2025-11-27 14:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_data', '0006_alter_mitredetectionstrategy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mitre_log_provider', models.CharField(blank=True, max_length=100)),
                ('mitre_channel', models.CharField(blank=True, max_length=100)),
                ('siem_product', models.CharField(default='Elasticsearch', max_length=100)),
                ('index_pattern', models.CharField(blank=True, help_text='e.g. winlogbeat-*', max_length=255)),
                ('coverage_status', models.CharField(choices=[('ACTIVE', 'Active'), ('PARTIAL', 'Partial'), ('MISSING', 'Missing')], default='ACTIVE', max_length=20)),
                ('mitre_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_data.mitredatacomponent')),
            ],
        ),
        migrations.CreateModel(
            name='LogField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_name', models.CharField(max_length=255)),
                ('siem_field_name', models.CharField(max_length=255)),
                ('field_type', models.CharField(default='keyword', max_length=50)),
                ('log_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='log_catalog.logsource')),
            ],
        ),
    ]
